### ISSUE TITLE
GLES 3 supported?

### ISSUE THREAD

**Issue by kircher1** [microsoft/angle#100]
Is ES 3 supported with ANGLE nuget package v2.1.11? eglCreateContext is failing when I try to specify a client version of "3". 

    const EGLint contextAttributes[] =
    {
        EGL_CONTEXT_CLIENT_VERSION, 3,
        EGL_NONE
    };

    // ....

    mContext = eglCreateContext(mDisplay, config, EGL_NO_CONTEXT, contextAttributes);
    if (mContext == EGL_NO_CONTEXT)
    {
        Ensures("Failed to create EGL context" && false);
    }

**Comment by sakrist** [comment]
I think your issue resolved here, https://github.com/Microsoft/angle/issues/91

**Comment by kircher1** [comment]
Thanks, that seems to work...

Per the bug, will rendering to the back buffer be supported for GL3? As pointed out in the docs, having to perform an additional full screen pass to mirror the buffer is not great for perf on lower end devices.

**Comment by austinkinross** [comment]
Hi there! This should be working in ANGLE NuGet package v2.1.11, which we published on Sept 25th. We didn't support this in v2.1.10, which was the latest version at the time issue #91 was resolved.

If I create a new project using the [VS Cross-Platform OpenGL ES template](https://blogs.msdn.microsoft.com/vcblog/2015/07/30/cross-platform-code-sharing-with-visual-c/), then I can successfully create a 3.0 context using NuGet package v2.1.11.

Could you confirm that you are using v2.1.11, and if so, could you share your full EGL initialization code?

Thanks!

**Comment by kircher1** [comment]
Thanks Austin. It's working for me now without disabling the back buffer optimization. Not sure what changed though. I am pretty sure the NuGet package was already v2.1.11.
