### ISSUE TITLE
MathHelper.h SimpleProjectionMatrix

### ISSUE THREAD

**Issue by pryorm92** [microsoft/angle#105]
I may have found an issue with SimpleProjectionMatrix. I was changing the near/far values, and my 3D model could not be seen with near/far of 0.01f/350.0f when the model was within 0.5f of my camera. The change I made to correct the issue was:

return Matrix4(cotangent / aspectRatio, 0.0f, 0.0f, 0.0f,
			0.0f, cotangent, 0.0f, 0.0f,
			0.0f, 0.0f, -(far + near) / (far - near), -1.0f,
			0.0f, 0.0f, 2.0f*(-far * near) / (far - near), 0.0f);

**Comment by austinkinross** [comment]
Hi pryorm92, I'm glad that you figured out how to correct your problem, and thanks for opening this issue.

MathHelper.h contains just enough math to get the spinning cube template working.  We didn't really intend for it to do anything more than the spinning cube in the template!

If you're writing your own app using ANGLE then I strongly recommend that you replace MathHelper.h with a complete math library instead, such as [DirectXMath](https://msdn.microsoft.com/en-us/library/windows/desktop/hh437833(v=vs.85).aspx) or [GLM](http://glm.g-truc.net/0.9.8/index.html).

**Comment by austinkinross** [comment]
Hi, we don't plan to fix this issue in the future. Please consider using another math library instead of relying on MathHelper.h. Thanks!
