### ISSUE TITLE
Only 30 FPS as standalone UWP app, 60 FPS with Visual Studio

### ISSUE THREAD

**Issue by realuptime** [microsoft/angle#109]
Hello,

I've been having my app for a year now in the store and it was always running at 60 frames per seconds on desktop.

Lately I discovered that it is running at 30 frames per second, and because of this I get negative reviews that my animations are not that smooth.

And this is very strange: If I start visual studio and open the xaml editor, my app will run again at 60 fps, no matter how many times I restart it. Closing visual studio while my app is running at 60 FPS, will make it drop to 30 again!

What is happening? What does this mighty editor do?

I am using SDL2 + standard SwapChainPanel.

I am 100% sure it's not my code that causes the frame drop and I am again sure that eglSwapBuffers makes the delay.

What steps will reproduce the problem?
1. Start the app with Visual Studio closed
2. App will have 30 fps.

What is the expected output? What do you see instead?
I always want 60 fps, not 30.

What version of the product are you using? On what operating system?
Latest Angle project from repository, Windows 10, 
Latest Update: Update for Windows 10 Version 1607 for x64-based Systems (KB3211320)

**Comment by realuptime** [comment]
Much easier steps to reproduce:
 - open in Chrome a webgl page (http://www.bongiovi.tw/experiments/webgl/blossom/), but don't maximize the window
 - start an Angle project UWP project (tried with my app and it happens the same)
 - make sure both apps are visible
 - see the cube rotation speed / fps speed are changing as you minimize and restore chrome. In my case with chrome and uwp app visible => both deliver 60 fps. With just the UWP app visible => 30 fps.

I think it has to do with the latest Game Mode support in windows 10, which should not be present at all in my opinion.

**Comment by realuptime** [comment]
After two days of investigation, it all breaks down to two VERY serious bugs since the KB3211320 update:
1. DirectX 11 apps running in UWP environment are capped to 30 frames per second.
Workaround: run another OpenGL / WEBGL (in Crome) application in parallel and make sure it is visible!
2. Benchmarking games in non-UWP environment by disabling vsync does not work anymore. They are capped at 60 frames per second.

Thank you,
Stan.

**Comment by austinkinross** [comment]
Hi Stan, I'm not able to reproduce this issue on two PCs with KB3211320 installed. Could you explain why you believe this is related to KB3211320?

It would be great if you could also share some more info:
 - What specs does your PC have? Is it a laptop or desktop? Which graphics card(s) does it have in it?
 - Can you share the exact OS build that you are running? If you type "About your PC" into the start menu search box and then run it, then you should see your "OS Build" amongst other information.
 - Have you been able to reproduce this exact behavior (i.e. minimizing/restoring chrome affecting the framerate) on other PCs? If so, what specs and OS build do they have?

Thanks a lot!
Austin

**Comment by realuptime** [comment]
Hi Austin,

Thank you for your help.

In the mean time I updated Intel HD 4600 driver from Asus and all seems fine, however disabling vsync keeps the fps to 60, but maybe that's another problem. I will close the issue.

I was thinking that this update caused this behavior since I did not change anything on my PC.
Here is someone else complaining about this update, and they refer to fps:
http://www.avsim.com/topic/502677-kb3211320-performance-drop/

In the mean time I tried to :
 - reinstall integrate video board driver - no luck
 - disable integrated board and use nvidia board - no luck
 - switch power plan to max performance - no luck
 - while running Android Studio it seems that the fps sticks to 60 (minimized or not)

Here are the specs:
OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	CATLINUX
System Manufacturer	ASUSTeK COMPUTER INC.
System Model	X550JK
System Type	x64-based PC
System SKU	ASUS-NotebookSKU
Processor	Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz, 2501 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. X550JK.303, 10/8/2014
SMBIOS Version	2.7
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	United States
Hardware Abstraction Layer	Version = "10.0.14393.206"
User Name	catlinux\Stan
Time Zone	GTB Standard Time
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.45 GB
Available Physical Memory	4.15 GB
Total Virtual Memory	11.9 GB
Available Virtual Memory	8.68 GB
Page File Space	4.50 GB
Page File	C:\pagefile.sys

Thank you again!
Stan.

**Comment by askanymark** [comment]
Any update on this? I noticed I have an issue with this if any UWP is in focus on my 144Hz GSync-enabled monitor, it will drop to 30 (or less, I'm not sure) FPS. A few examples: Xbox store for PC (where you have the game pass thing), Spotify, Bethesda launcher. This doesn't happen if it's on my 2nd monitor which is a classic 60Hz one. Can provide more info if needed.
