### ISSUE TITLE
Does it support dds(dxt3) hardware decoding in wp8?

### ISSUE THREAD

**Issue by rickdu** [microsoft/angle#11]
I tested a dds file with dxt3 format using  cocos2d-x v3.0 on windows phone 8, but found it decoded by software.
If it's possible to make the dds file decoded by hardware if using ANGLE?
Thanks!

**Comment by stammen** [comment]
We are looking into adding DDS hardware support this fall.

**Comment by austinkinross** [comment]
Hi,

This issue applies to the Windows Phone 8.0 version of ANGLE, which has moved to https://github.com/MSOpenTech/angle-win8.0. Please create an issue in that repository if you wish to discuss the 8.0 version of ANGLE.

Thanks,
Austin

**Comment by ghost** [comment]
Sorry, does this mean that Windows/Phone 8.1 already supports hardware decoding of DDS?

**Comment by austinkinross** [comment]
Hi sqpat,

Our 8.1 version of ANGLE doesn't support loading DDS files directly, but it should support the DXT1, DXT3 and DXT5 extensions (e.g. GL_ANGLE_texture_compression_dxt3). To load a DDS file, your app will have to read the file itself, and make appropriate GL calls with the data.

The DirectX Tool Kit (DirectXTK) includes DDSTextureLoader, which is a helper to load DDS files as DirectX textures. We plan to write a version of this for ANGLE in the future, but I can't predict when that will happen.

If you would like us to write this ANGLE DDSTextureLoader soon then please feel free to file another issue on this GitHub repo.

Thanks,
Austin

**Comment by ghost** [comment]
Thanks for the info. I decided to downscale my textures instead - I
actually use webp for low disk usage and lossy variable alpha support. So i
have software decoding anyway, mostly I wanted to benefit from in memory
compression. I may revisit DXT3/5 again later but its not a big priority.
- Patrick
