### ISSUE TITLE
Which fork for Desktop? (MS vs Google)

### ISSUE THREAD

**Issue by mattleibow** [microsoft/angle#112]
I am wanting to build ANGLE for packaging with classic desktop https://github.com/mono/SkiaSharp. I was wondering what fork will be best. MS has been doing work on the https://github.com/Microsoft/angle fork, but there appears to be several extra commits on the https://chromium.googlesource.com/angle/angle/ repo. 

Is it just because MS hasn't pulled from upstream recently, or is the work diverging? If I am going for classic desktop, where is the best place to build from?

**Comment by austinkinross** [comment]
Hi! The vast majority of changes in Microsoft/angle have been pushed upstream, so these days there isn't much difference between the branches. We still recommend using Microsoft/angle for Windows Store apps, but for desktop you should use whichever is easiest for you. 

One small difference is that Microsoft/angle contains pre-generated Visual Studio projects, while the upstream branch will require you to run some tools to generate your own projects.

Thanks,
Austin
