### ISSUE TITLE
OpenGL ES 3.1?

### ISSUE THREAD

**Issue by ghost** [microsoft/angle#113]
Hello. Will Microsoft ANGLE supports OpenGL ES 3.1? Will compute shaders over DirectCompute?

**Comment by austinkinross** [comment]
Hi! Other companies such as Intel are working on support for OpenGL ES 3.1 in the master ANGLE repository. You may wish to ask about the status of that effort on [these discussion forums](https://groups.google.com/forum/#!forum/angleproject).

Microsoft ANGLE takes merges from the master ANGLE repository every so often, so we will support OpenGL ES 3.1 shortly after it is supported in master.

Thanks!
Austin
