### ISSUE TITLE
Performance issues with Angle 2.1.14

### ISSUE THREAD

**Issue by johanlindfors** [microsoft/angle#116]
We are having serious performance issues in our apps/games when upgrading to 2.1.14 of Angle. Issues seems to not appear in Angle 2.1.13. We are seeing sluggish behavior when starting animations, input responds, sounds play, but it takes almost half a second for animations to begin playing.

This is most visible (unplayable) in Lumia 1320, 550 and 640, but we also get similar behavior on desktop PC.

For now we downgrade to 2.1.13. Wonder if this is related to #111

**Comment by austinkinross** [comment]
Thanks for reporting this Johan! Apologies for the delayed reply-- I've been oof on vacation. I spoke to Jaime briefly last week about this; hopefully he spoke to you after that?

In short, we recommend using 2.1.13 for now. We've removed 2.1.14 from NuGet pending further investigation, and we will ship a new NuGet package in the future with a better workaround for issue #111.

Thanks again,
Austin
