### ISSUE TITLE
GLFW with ANGLE (software)

### ISSUE THREAD

**Issue by mumin16** [microsoft/angle#117]
#define GL_GLEXT_PROTOTYPES
#include <angle_gl.h>
#pragma comment(lib,"libGLESv2")
#define GLFW_DLL
#define GLFW_INCLUDE_NONE	
#include <glfw/glfw3.h>
#pragma comment(lib,"glfw3dll")

#include <stdlib.h>
#include <stdio.h>

GLuint g_programObject;

GLuint LoadShader(GLenum type, const char *shaderSrc)
{
	GLuint shader;
	GLint compiled;

	// Create the shader object
	shader = glCreateShader(type);

	if (shader == 0)
	{
		return 0;
	}

	// Load the shader source
	glShaderSource(shader, 1, &shaderSrc, NULL);

	// Compile the shader
	glCompileShader(shader);

	// Check the compile status
	glGetShaderiv(shader, GL_COMPILE_STATUS, &compiled);

	if (!compiled)
	{
		GLint infoLen = 0;

		glGetShaderiv(shader, GL_INFO_LOG_LENGTH, &infoLen);

		if (infoLen > 1)
		{
			char *infoLog = (char *)malloc(sizeof(char) * infoLen);

			glGetShaderInfoLog(shader, infoLen, NULL, infoLog);

			free(infoLog);
		}

		glDeleteShader(shader);
		return 0;
	}

	return shader;

}

bool Init()
{
	char vShaderStr[] =
		"attribute vec4 vPosition;  \n"
		"void main()                              \n"
		"{                                        \n"
		"   gl_Position = vPosition;              \n"
		"}                                        \n";

	char fShaderStr[] =
		"precision mediump float;                     \n"
		"void main()                                  \n"
		"{                                            \n"
		"   gl_FragColor = vec4 ( 1.0, 0.0, 0.0, 1.0 );  \n"
		"}                                            \n";

	GLuint vertexShader;
	GLuint fragmentShader;
	GLuint programObject;
	GLint linked;

	// Load the vertex/fragment shaders
	vertexShader = LoadShader(GL_VERTEX_SHADER, vShaderStr);
	fragmentShader = LoadShader(GL_FRAGMENT_SHADER, fShaderStr);

	// Create the program object
	programObject = glCreateProgram();

	if (programObject == 0)
	{
		return 0;
	}

	glAttachShader(programObject, vertexShader);
	glAttachShader(programObject, fragmentShader);

	// Link the program
	glLinkProgram(programObject);

	// Check the link status
	glGetProgramiv(programObject, GL_LINK_STATUS, &linked);

	if (!linked)
	{
		GLint infoLen = 0;

		glGetProgramiv(programObject, GL_INFO_LOG_LENGTH, &infoLen);

		if (infoLen > 1)
		{
			char *infoLog = (char *)malloc(sizeof(char) * infoLen);

			glGetProgramInfoLog(programObject, infoLen, NULL, infoLog);

			free(infoLog);
		}

		glDeleteProgram(programObject);

		return false;
	}

	// Store the program object
	g_programObject = programObject;

	glClearColor(1.0f, 1.0f, 1.0f, 0.0f);

	return true;
}

static void error_callback(int error, const char* description)
{
	fputs(description, stderr);
}

static void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods)
{
	if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
		glfwSetWindowShouldClose(window, GL_TRUE);
}

int main()
{
	GLFWwindow* window;

	glfwSetErrorCallback(error_callback);
	if (!glfwInit())
		exit(EXIT_FAILURE);
	glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 2);//or 3
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);
	glfwWindowHint(GLFW_CLIENT_API, GLFW_OPENGL_ES_API);

	window = glfwCreateWindow(640, 480, "GLFW with ANGLE (software)", NULL, NULL);
	int result = glfwGetWindowAttrib(window, GLFW_CLIENT_API);

	if (!window)
	{
		glfwTerminate();
		exit(EXIT_FAILURE);
	}

	glfwMakeContextCurrent(window);
	glfwSwapInterval(1);
	glfwSetKeyCallback(window, key_callback);

	printf("%s", glGetString(GL_VERSION));

	if (!Init())
		return 0;

	while (!glfwWindowShouldClose(window))
	{
		float ratio;
		int width, height;
		glfwGetFramebufferSize(window, &width, &height);
		ratio = width / (float)height;

		GLfloat vVertices[] = { 0.0f,  0.5f, 0.0f,
			-0.5f, -0.5f, 0.0f,
			0.5f, -0.5f, 0.0f
		};

		glViewport(0, 0, width, height);

		glClear(GL_COLOR_BUFFER_BIT);

		// Use the program object
		glUseProgram(g_programObject);

		// Load the vertex data
		glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 0, vVertices);
		glEnableVertexAttribArray(0);

		glDrawArrays(GL_TRIANGLES, 0, 3);

		glfwSwapBuffers(window);
		glfwPollEvents();
	}

	glfwDestroyWindow(window);
	glfwTerminate();
	exit(EXIT_SUCCESS);
}

**Comment by austinkinross** [comment]
Hi, do you have a specific question or issue with this code?

**Comment by mumin16** [comment]
i want use to only dx9-es2. es2 is ok but it loads dx11 too... why?

**Comment by austinkinross** [comment]
Hi, this Microsoft/ANGLE respository is typically focused on ANGLE's DirectX 11 back-end. For help with the DirectX 9 back-end I recommend asking over on the master ANGLE project discussion page: https://groups.google.com/forum/#!forum/angleproject

Feel free to open another issue here if you're having trouble with something else in ANGLE.

Best wishes,
Austin
