### ISSUE TITLE
glProgramBinary crash

### ISSUE THREAD

**Issue by alek314** [microsoft/angle#119]
ensureHLSLCompilerInitialized is not called if all shader is shader binary,  i have to compile at least one shader from source to make mCompiler initialize properly.

**Comment by austinkinross** [comment]
Thanks for reporting this alek314! Would you mind creating a bug for this over on the master ANGLE project bug page? https://bugs.chromium.org/p/angleproject/issues/list

Thanks!

**Comment by alek314** [comment]
bug created on chromium.org:
https://bugs.chromium.org/p/angleproject/issues/detail?id=2010

**Comment by austinkinross** [comment]
Thanks a lot!

I'm closing this issue on Microsoft\ANGLE since there is now an active bug on the master ANGLE project. We'll pick up the fix in Microsoft\ANGLE in due course, once it's fixed in the master ANGLE project.
