### ISSUE TITLE
Extensions - GL_EXT_shader_framebuffer_fetch, GL_EXT_shader_texture_lod

### ISSUE THREAD

**Issue by damanjit81** [microsoft/angle#13]
Are these extensions  supported on a Windows 8.1 Desktop / Surface?
1. GL_EXT_shader_framebuffer_fetch
2. GL_EXT_shader_texture_lod

These do not work for me when I use them in a shader. I get "extension not supported" error.

**Comment by coopp** [comment]
We will look more into this.  I need to get a better understanding of where these extensions fit in the current code.  

Did these extensions work for you on Windows 8, or classic desktop?

**Comment by damanjit81** [comment]
Hi,

I did not try in classic mode, nor on Windows 8. I am only targeting Windows store apps. Basically porting my iPAD app for Windows store.

**Comment by damanjit81** [comment]
Hi,

Just curious to know if you found any suggestions for me. I believe these extensions aren't supported yet. Is it?

**Comment by coopp** [comment]
Hi,
It doesn't look like GL_EXT_shader_framebuffer_fetch is currently implemented.  GL_EXT_shader_texture_lod has some more implementation but I am not sure if it is fully implemented yet.  We can add this item as something to possibly implement in the future.

**Comment by damanjit81** [comment]
It would be great to have these extensions available in ANGLE. My app depends on these. Could you please log an enhancement request for the same.

Thanks,
Daman

**Comment by coopp** [comment]
I will get this onto our backlog so we can investigate further.  I am not sure exactly when we will address this item, but I will make sure it gets on our list to look into.

Thanks,
Coop
