### ISSUE TITLE
Provide a Visual Studio configuration to produce static libraries

### ISSUE THREAD

**Issue by PhilFCGB** [microsoft/angle#135]
For some projects using ANGLE, it would be useful to have direct static libraries generated by a Visual Studio configuration instead of dynamic libraries (we only have dll projects in current Visual Studio configurations).

For example: we can have a tool generating executables using ANGLE and we want to exchange this executable with someone, it would not be possible without providing libEGL.dll and libGLESv2.dll.

**Comment by austinkinross** [comment]
Hi, apologies for the delayed reply. 

We don't intend to make modifications like this to ANGLE, in either our local repository or in the upstream master repository. Please consider making this request to a broader audience in the master ANGLE discussion group here: https://groups.google.com/forum/#!forum/angleproject

Thanks!
Austin
