### ISSUE TITLE
Issue when using Windows::Media::Editing::MediaComposition API to create video from ANGLE (UWP)

### ISSUE THREAD

**Issue by simplyzhao** [microsoft/angle#137]
Hi, we have a UWP app using ANGLE(combined with SwapChainPanel) to render canvas.
We'd like to implement a feature that record a video(includes content on SwapChainPanel only) based on user's drawing process.
The basic idea is to create a IDirect3DSurface whenever ANGLE renders a new frame, then add it to the MediaComposition by creating a MediaClip, and finally we'll get a video.
By following the article below, we're able to create the IDirect3DSurface for every frame:
https://github.com/Microsoft/angle/wiki/Interop-with-other-DirectX-code

However, the final video contains all the last frame, instead of each frame.
Do you have any idea how to achieve this?

The following code creates IDirect3DSurface for every frame and add to MediaComposition:

```
    ComPtr<IDXGISurface> dxgiSurface;
    HRESULT hr = mOffscreenSurfaceD3D11Texture.As(&dxgiSurface);
    auto d3dsurface = Windows::Graphics::DirectX::Direct3D11::CreateDirect3DSurface(dxgiSurface.Get());
    TimeSpan t;
    t.Duration = 160000; // 16 ms
    mComposition->Clips->Append(MediaClip::CreateFromSurface(d3dsurface, t));
```

**Comment by austinkinross** [comment]
Hi there, this is unfortunately outside my area of expertise. I suggest asking over on the DirectX Discord channel (https://devblogs.microsoft.com/directx/hello-discord/) if you still have questions about this topic.

Thanks!
Austin
