### ISSUE TITLE
libEGL.dll from intel driver mess up with Angle

### ISSUE THREAD

**Issue by alek314** [microsoft/angle#139]
Intel's graphics driver seems to install it's own version of libEGL.dll in Windows\SysWow64. In some case the app will load intel's dll and lead to a crash.

**Comment by austinkinross** [comment]
Hi, 

I believe this issue impacts all ANGLE users and not just our repository, so please report this to the upstream master repository here: https://groups.google.com/forum/#!forum/angleproject

Thanks!
Austin
