### ISSUE TITLE
ANGLE_ENABLE_RENDER_TO_BACK_BUFFER causes error code to glGetError

### ISSUE THREAD

**Issue by amerkoleci** [microsoft/angle#14]
I was playing arround with ANGLE_ENABLE_RENDER_TO_BACK_BUFFER and seams that when I enable ANGLE_ENABLE_RENDER_TO_BACK_BUFFER when I call glDrawElements I'm getting an error, if define is disabled it works fine.

**Comment by coopp** [comment]
This is very interesting.  We will take a look immediately.  glDrawElements should work when that #define is enabled.  We will get back to you as soon as we investigate this issue.

Thanks for reporting this!

**Comment by austinkinross** [comment]
Did you enable ANGLE_ENABLE_RENDER_TO_BACK_BUFFER in all of the ANGLE projects, or just libGLESv2? It must be set in all of them.

**Comment by amerkoleci** [comment]
I ve enabled it on libGLESv2, i saw you made changes only there

**Comment by coopp** [comment]
I think compiler\translator\OutputHLSL.cpp also has changes as well which is what you may be missing here.

**Comment by coopp** [comment]
OutputHLSL.cpp is compiled in the translator_lib project which is probably missing the #define.

**Comment by amerkoleci** [comment]
Ok, by adding defines to translator_lib, libEGL and libGLESv2 it works fine.
