### ISSUE TITLE
angle does not build correctly when down load as a zip file

### ISSUE THREAD

**Issue by alek314** [microsoft/angle#142]
There is a bug in commit_id.py. 
When ANGLE is down load as a zip file, no git info is available.
And grap_output("git ...") will return a empty string, but no exception is thrown.
Which results in empty commit_id and commit_date, but they should be 'invalid-hash' and 'invalid-date'

**Comment by austinkinross** [comment]
Hi there, thank you for reporting this. Going forward we suggest that you use build (and use) ANGLE from the main ANGLE repository instead: https://opensource.google.com/projects/angle

Thanks
Austin
