### ISSUE TITLE
glPushGroupMarkerEXT is not spec-compliant

### ISSUE THREAD

**Issue by lunasorcery** [microsoft/angle#145]
From [the spec](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_debug_marker.txt):

    The command
    
        void PushGroupMarkerEXT(sizei length, const char *marker);
        
    pushes a group marker string <marker> into the command stream. <length> 
    specifies the length of the string passed in <marker>. If <marker> is a 
    null-terminated string then <length> should not include the terminator. If 
    <length> is 0 then <marker> is assumed to be null-terminated. If <marker> 
    is null then an empty string is pushed on the stack.

However ANGLE treats ``length = 0`` as specifying an empty string, rather than the null-terminated case.

See the implementation of ``Context9::pushGroupMarker`` and ``Context11::pushGroupMarker``, both of which call into ``angle::WidenString`` which does not account for this expected behavior.

**Comment by austinkinross** [comment]
Hi, thanks for the report. This is an issue in the main master ANGLE repo too-- could you report the issue over there (https://bugs.chromium.org/p/angleproject/issues/list)? We'll pick up the fix here in the future after it's fixed in master.

Thanks!
Austin

**Comment by austinkinross** [comment]
I'm closing this issue since we won't fix it directly in this repo-- the fix should go into master ANGLE repo instead.

Thanks again for reporting this!
