### ISSUE TITLE
Compilation error for samplers.sln due to macro SHADER_SOURCE missing

### ISSUE THREAD

**Issue by WoodRain** [microsoft/angle#148]
Open samples/samples.sln using VS2015 and build the entire solution, then there're compilation errors complaining about that SHADER_SOURCE is missing in texture_loading_dds and texture_loading_wic projects. Define a macro for it or use C++11 raw string will solve the problem. [Here's ](https://gist.github.com/WoodRain/99a04ff410c79ba9f5a881cd16447c92)the diff used.

**Comment by austinkinross** [comment]
Thanks for reporting this! 

texture_loading_dds and texture_loading_wic are two samples that we haven't submitted to the master ANGLE repository yet.  They were probably broken during our last merge from master-- for example, SHADER_SOURCE might have been removed without us noticing.

We'll try to fix this soon. Thanks again.

**Comment by austinkinross** [comment]
Hi, apologies that we didn't get to fix this. These samples have now been deprecated, although they are still available over in [this branch](https://github.com/microsoft/angle/tree/2017-lkg) as a reference.
