### ISSUE TITLE
Question regarding shaders

### ISSUE THREAD

**Issue by cjd22** [microsoft/angle#153]
Hi,I am trying to render to a texture. The shaders set up for rendering but when I try to draw nothing is drawn. I am including the gl3.h files. I am rendering to textures and alpha blending is turned on but nothing is being drawn. Is there an issue with the shaders? Please advise. Thank you in advance. Why is my question being ignored

**Comment by austinkinross** [comment]
Hi there, apologies for the delayed reply here. If you're still having this issue then I suggest that you ask about it over on the main ANGLE repository's mailing list here: https://groups.google.com/forum/#!forum/angleproject
