### ISSUE TITLE
[Feature Request] Allow feature level 10.0 to use OpenGL ES 3.0

### ISSUE THREAD

**Issue by flibitijibibo** [microsoft/angle#155]
On Xbox One, we're only allowed to use D3D11 with feature level 10.0, which currently restricts us to ES2. This is surprisingly hard to work with because this forcibly cuts out a TON of features, but on the other hand all 10.0 is really missing from the spec is cubemap arrays. If we promote 10.0 to ES3, everything works just fine:

https://github.com/FNA-XNA/angle/commit/564d72f4ff67ede8fc82908e716ab7f0e8dd601b

I think a lot of people developing for Xbox would be okay with having cubemap arrays as the main unsupported feature, and it could be documented alongside the other ES conformance issues:

https://github.com/Microsoft/angle/wiki/Known-Issues

**Comment by ghost** [comment]
An updates here? I am trying does the support for ES3 on xbox exist in future plans?

**Comment by austinkinross** [comment]
Hi there, going forward we strongly recommend that you build (and use) ANGLE from the main ANGLE repository.

If you are still interested in this change then please consider asking about it over on the main ANGLE mailing list here: https://groups.google.com/forum/#!forum/angleproject

Thanks
Austin
