### ISSUE TITLE
Assertion failed when call eglInitialize

### ISSUE THREAD

**Issue by harlanc** [microsoft/angle#158]
My platform is win10 

warning: Assertion failed!

Program: C:\MinGW\msys\1.0\local\bin\libGLESv2.dll
File: libANGLE\renderer\d3d\d3d11\Renderer11.cpp
Line: 1172

Expression: configs.size() > 0

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)

Program received signal SIGTRAP, Trace/breakpoint trap.
0x5c8ad7f7 in libGLESv2!glProgramUniform2fv () from C:\MinGW\msys\1.0\local\bin\libGLESv2.dll

**Comment by harlanc** [comment]
I run the demo DesktopHelloTriangle, the above error also happens.

Using Vistual studio  community 2015 on windows 10
<img width="474" alt="2018-11-24 5 42 01" src="https://user-images.githubusercontent.com/10411078/48966634-6b96fb80-f010-11e8-8fa5-dccaf971b7be.png">

Update:

The demo can be run successfully on physical machine. The Assert error only happens on virtual
machine...

**Comment by austinkinross** [comment]
Hi there, apologies for the delayed reply here. 

I'm afraid that I don't know what could be causing that. If you are still experiencing problems then I suggest that you ask about them on the master ANGLE mailing list: https://groups.google.com/forum/#!forum/angleproject

Thanks
Austin
