### ISSUE TITLE
Missing ARM64 support in NuGet ANGLE.WindowsStore package

### ISSUE THREAD

**Issue by dmitrykos** [microsoft/angle#163]
Recently Microsoft announced ARM64 support:
http://blogs.windows.com/buildingapps/2018/11/15/official-support-for-windows-10-on-arm-development/

Currently ANGLE.WindowsStore NuGet package (latest, 2.1.13) does not include binaries for ARM64 architecture, although it would be really useful to have it in order for apps using OpenGL support ARM64 architecture and thus provide more performance optimal apps to the end-user devices.

Currently apps using OpenGL via Angle can only distribute ARMv7 binaries to ARMv8 (ARM64) devices that is suboptimal.

Can ANGLE.WindowsStore NuGet package be updated with ARM64 architecture?

**Comment by mtehver** [comment]
There seems to be even a PR for this. Would very much appreciate if this would be released as NuGet package.

**Comment by austinkinross** [comment]
Hi there, unfortunately we don't have any plans to update the ANGLE NuGet package. 

We strongly recommend that you build ANGLE directly from the main ANGLE repository instead: https://opensource.google.com/projects/angle

I believe that the main ANGLE repository supports building ARM64 for desktop Windows. If so, then I suspect that ARM64 UWP builds will "just work" or will only require a small change.

Thanks
Austin
