### ISSUE TITLE
D3D11On12CreateDevice

### ISSUE THREAD

**Issue by jhhsia** [microsoft/angle#167]
Hi,

    Wondering if it's possible to simply use D3D11On12CreateDevice and have a DX12 based backend to render for Angle.

**Comment by austinkinross** [comment]
Yes, this should be possible. You may need to modify ANGLE slightly to use D3D11on12CreateDevice instead of D3D11CreateDevice though.

Please post any future questions on this topic to the master ANGLE group: https://groups.google.com/forum/#!forum/angleproject

- Austin
