### ISSUE TITLE
Support native OpenGL

### ISSUE THREAD

**Issue by dxgldotorg** [microsoft/angle#169]
Certain GPU drivers, like NVIDIA, have native OpenGL drivers whose performance is competitive with that of DirectX.  Because of this, consider supporting native OpenGL, both in desktop and update Windows 10 to support it in UWP.

**Comment by fghzxm** [comment]
https://chromium.googlesource.com/angle/angle says native OpenGL backend is already functional for GLES versions up to 3.1 on Windows, Linux and macOS.

**Comment by dxgldotorg** [comment]
I did suggest that UWP's limitations be loosened a bit to allow native GL within its restricted environment too.

**Comment by austinkinross** [comment]
Hi there, thanks for the suggestion. Unfortunately we're not the right people to help with this request. Please consider making this request over on the DirectX Discord instead, perhaps in the "developer-feedback" or "feature-requests" channels. That will help direct your requests to the right people/teams in Microsoft.
