### ISSUE TITLE
Bad performance due to D3D_FEATURE_LEVEL_10_0

### ISSUE THREAD

**Issue by diamond-msc** [microsoft/angle#2]
Tracking an FPS drop from 60 to 7 on the cocos2d-x HelloWorld (cocos 2.2 vs. 2.2.1) I hunted down 1377528c4395ded43b01eb2adbc9b733fc4faa5a

On my System (Win 8.1 64bit, VS2013, Intel(R) HD Graphics) `D3D_FEATURE_LEVEL_10_0` is the cause of bad performance.

This may be a driver issue but since the angleproject states _translating OpenGL ES 2.0 API calls to DirectX 9 or DirectX 11 API calls_ it could be considered a bug.

**Comment by stammen** [comment]
Are you using the winrt branch? The code you referenced in your report no longer exists. Please verify what code you  are using. Also, are you using the latest master branch of cocos2d-x? Thanks.

**Comment by diamond-msc** [comment]
The referenced commit was the change that broke performance for me.

I'm on the latest cocos2dx (https://github.com/MSOpenTech/cocos2d-x/commit/5118630c103c63080932d0d6c29cab15046329c1)
The line I commented out as a workaround is https://github.com/MSOpenTech/angle/blob/winrt/src/libGLESv2/renderer/Renderer11.cpp#L158

**Comment by stammen** [comment]
Thanks for the info. After commenting out Level_10_0 what level is returned in mFeatureLevel in the call to D3D11CreateDevice?

?

**Comment by diamond-msc** [comment]
`D3D_FEATURE_LEVEL_9_1`

**Comment by stammen** [comment]
Thanks for the info. I will investigate when I am back in the office on Jan 6.

**Comment by feriahegyrul** [comment]
We are also experiencing performance problems under win 8.1 (cocos2d-x 2.2.2), in HD resolution displaying only a single background image in a CCLayerColor drops the freamerate to 40 FPS. Is this a known issue? If it is, when will this performance problem be resolved?

PS: uncommenting D3D_FEATURE_LEVEL_10_0 did not work for us.

**Comment by stammen** [comment]
We are looking into the reduced fps on high resolution devices.

**Comment by diamond-msc** [comment]
Just tested https://github.com/MSOpenTech/cocos2d-x/commit/1941bea5638fcfa5e4448d7c09d623831b119368 on https://github.com/MSOpenTech/cocos2d-x/tree/universal with https://github.com/MSOpenTech/angle/commit/9eaccd68172a64f8b3c25931e7fbd535312d4515 on https://github.com/MSOpenTech/angle/tree/winrt-es3proto

Performance is good in my case (1280x800) with release build settings. Hello World is back at 60 FPS!
Most Cocos2D tests have equal or better performance with `LEVEL_ANY` than `LEVEL_9_1` in recent `v2`. (Exceptions I found are tests with high (e. g. 170) GL call count.)
