### ISSUE TITLE
Textures appear not to work on phone?

### ISSUE THREAD

**Issue by schlomer** [microsoft/angle#20]
For future dev branch on Windows Phone 8.1 I can't get 2d texture rendering to work when deployed to a phone (ARM build).
Win32 targets, such as phone simulator, local machine, and tablet simulators render a simple 2d texture mapped pair of triangles fine.
Anyone else have problems with this? I can provide example code if needed as not sure if this is an open issue or not or if there are some preprocessor defines/config items I need in the ARM configuration.

**Comment by coopp** [comment]
How recent did you pull the latest future-dev branch?  To help narrow down the problem a small change change be made in your application's call to eglGetDisplay or eglGetPlatformDisplayExt to force your local machine and simulators to use Feature Level 9_3 which matches what the phone should be using.

**Comment by coopp** [comment]
Example code would be great too.  

To force your application to use FL9_3, you can update the displayAttributes being passed to eglGetPlatformDisplayEXT.

const EGLint displayAttributes[] =
{
EGL_PLATFORM_ANGLE_TYPE_ANGLE, EGL_PLATFORM_ANGLE_TYPE_D3D11_FL9_3_ANGLE,
EGL_NONE,
};

mEglDisplay = eglGetPlatformDisplayEXT(EGL_PLATFORM_ANGLE_ANGLE, EGL_DEFAULT_DISPLAY, displayAttributes);

**Comment by schlomer** [comment]
Thanks for the info. I downloaded the future-dev ZIPped code yesterday. What triggered yesterday's download was a version prior wasn't working for this either. It seems from my results below that there is something in the FL9_3 path not quite right. I've tried 64x64 and 256x256 textures (just to experiment).

Here are my results when using eglGetPlatformDisplayEXT with different platform types. Images attached down below:
EGL_PLATFORM_ANGLE_TYPE_D3D11_WARP_ANGLE - Works in Win32 local and simulator
EGL_PLATFORM_ANGLE_TYPE_D3D11_ANGLE - Works in Win32 local and simulator
EGL_PLATFORM_ANGLE_TYPE_D3D11_FL9_3_WARP_ANGLE - Does _not_ work in Win32 local or simulator
EGL_PLATFORM_ANGLE_TYPE_D3D11_FL9_3_ANGLE - Does _not_ work in Win32 local or simulator or ARM

Here are the shaders I'm using. They're pretty basic:

static std::string vs = "attribute vec4 a_position;\n"
        "attribute vec2 a_texCoord;\n"
        "uniform mat4 u_projectionViewMatrix;\n"
        "varying vec2 v_texCoords;\n"
        "\n"
        "void main()\n"
        "{\n"
        "   v_texCoords = a_texCoord;\n"
        "   gl_Position =  u_projectionViewMatrix \* a_position;\n"
        "}\n";

```
static std::string fs =
    "precision mediump float;\n"
    "varying vec2 v_texCoords;\n"
    "uniform sampler2D u_texture;\n"
    "void main()\n"
    "{\n"       
    "gl_FragColor = texture2D(u_texture, v_texCoords);\n"
    "}";
```

Turning on blending makes the box totally _disappear_ on FL9_3 platforms, but on straight D3D11 platforms, the texture is transparent where it should be:
glEnable(GL_BLEND); 
glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

Both glTexImage2D with either GL_RGBA or GL_BGRA_EXT work with D3D11, but neither work with FL9_3 on either Win32 or ARM:
glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, image->Width(), image->Height(), 0, GL_RGBA, GL_UNSIGNED_BYTE, image->Data());

glTexImage2D(GL_TEXTURE_2D, 0, GL_BGRA_EXT, image->Width(), image->Height(), 0, GL_BGRA_EXT, GL_UNSIGNED_BYTE, image->Data());

Using VBOs or not doesn't seem to change the results. I am not getting any errors with glGetError in any of the setup or rendering calls.

Hope some of this info helps. 

BLEND ON D3D11 (this is what it should look like on the phone too):
![image_blendon_egl_platform_angle_type_d3d11_angle](https://cloud.githubusercontent.com/assets/8675347/4547267/765c3b72-4e4b-11e4-9ce0-89d6a28c9e42.png)

BLEND OFF D3D11:
![image_egl_platform_angle_type_d3d11_angle](https://cloud.githubusercontent.com/assets/8675347/4547127/1b4b1d1c-4e4a-11e4-8ce0-ce371c901e56.png)

FL9_3_ANGLE:
![image_egl_platform_angle_type_d3d11_fl9_3_angle](https://cloud.githubusercontent.com/assets/8675347/4547126/1ad409ca-4e4a-11e4-8320-884d3782d822.png)

FL9_3_WARP_ANGLE:
![image_egl_platform_angle_type_d3d11_fl9_3_warp_angle](https://cloud.githubusercontent.com/assets/8675347/4547125/1acb25f8-4e4a-11e4-906f-ef09056fff10.png)

**Comment by austinkinross** [comment]
Hi! Thanks a lot for reporting this issue. 

What size is the texture that you're sampling from, and how big is the screen area that you're rendering the texture to? Could you try repro'ing the issue with a texture that is much smaller than the screen area that it's rendered to, i.e. so the texture gets magnified?

My suspicion is that you're hitting a 9_3 texture issue that we're aware of. We're actually working on that right now, and hope to have a fix soon.

Thanks,
Austin

**Comment by schlomer** [comment]
Well, there is some good news: I can get a 1x1 texture to render on 9_3, both Win32 and ARM :-)
Anything above 1x1 dimensions (even 2x2, 4x4, etc) doesn't work on 9_3 in either Win32 or ARM.
As for screen resolution, the phone is a Nokia 1520, so 1080P, and I've also been using the various sized phone/tablet emulators. The local machine has a 1080P monitor.

**Comment by austinkinross** [comment]
Okay, thanks for trying that! :-)

I still suspect that you're hitting the know 9_3 texture issue. I hope to have a fix for this available in future-dev early next week. If this fix doesn't solve your problem then I'll be happy to work with you so I can reproduce (and debug) the issue.

In the meantime, if you're blocked by this issue then I think you can workaround it by modifying ANGLE slightly. In the file "\src\libGLESv2\renderer\d3d\TextureD3D.cpp", try removing the current implementation of "TextureD3D::creationLevels(...)", and make the method always return 1. I wouldn't recommend shipping like this but it might help you unblock development.

Thanks again,
Austin

**Comment by schlomer** [comment]
Schweet. That worked!
Thanks

**Comment by austinkinross** [comment]
I just pushed a fix for the known 9_3 texture issue to future-dev. Would you mind undoing the "return 1" workaround, syncing to the latest version of the future-dev branch, and trying to reproduce your issue?

**Comment by schlomer** [comment]
Excellent. That works. I got your latest; both eglGetPlatformDisplayEXT (using EGL_PLATFORM_ANGLE_TYPE_D3D11_FL9_3_ANGLE) worked and so did reverting back to just using eglGetDisplay(EGL_DEFAULT_DISPLAY).

I'll let you know if I find anything else.

Thanks!

**Comment by austinkinross** [comment]
Thanks schlomer. I'm glad it's fixed.

Do let us know if you find anything else!
