### ISSUE TITLE
Add support for XBox One

### ISSUE THREAD

**Issue by amerkoleci** [microsoft/angle#21]
Do you plan to add support for Xbox One?
 I'm not sure if it supports runtime shader compilation.

**Comment by coopp** [comment]
We haven't started any work on ANGLE to target Xbox One, but it is on our list to look into and investigate what that means and involves.

**Comment by pulcheri** [comment]
Just wondering if there is any update on this. Considering that there is this push for "one, unified platform" it would make sense to support Xbox One as well.

**Comment by zhaijialong** [comment]
@montonero 
It's possible to port angle to xbox one yourself. In fact I finished the work in about one week last year, and it works well, it's not that hard. But I think I can't publish it due to Microsoft's privacy policy. And now the porting work should be much more simple, because the xbox one sdk supports vs2015 now(only 2012 before which doesn't support many c++11 features used in angle).

**Comment by austinkinross** [comment]
ANGLE fully supports Windows 10's Universal Windows Platform (UWP), and ANGLE works as expected on versions of Windows 10 which support the UWP, such as Desktop, Mobile and IoT devices.

The Xbox One doesn't currently support UWP apps, but support is coming in the future. At that point, ANGLE should "just work" on the Xbox One, and we will test it to make sure that it does.

For details of when the Xbox One will support UWP, please see other Microsoft sources such as this: http://www.xbox.com/en-us/Developers/id

Thanks!

**Comment by AlexVK79** [comment]
> @montonero
> It's possible to port angle to xbox one yourself. In fact I finished the work in about one week last year, and it works well, it's not that hard. But I think I can't publish it due to Microsoft's privacy policy. And now the porting work should be much more simple, because the xbox one sdk supports vs2015 now(only 2012 before which doesn't support many c++11 features used in angle).

What's the privacy policy you mentioned that prevents/prevented using ANGLE on XBox?
