### ISSUE TITLE
Any thoughts on merging with official google angle project?

### ISSUE THREAD

**Issue by amerkoleci** [microsoft/angle#22]
Hi,
I saw this commit (https://chromium.googlesource.com/angle/angle/+/88d3b8cb737f3f4662e421bd2b1004a458fdf2a1), does this mean that the project will be merged with google's one?

Thanks

**Comment by coopp** [comment]
Improvements and features authored in Future-dev are being pushed to Google's mainline ANGLE branch yes.  These are done on a case by case basis.  The Future-dev branch does occasionally pick up the latest changes from Google's mainline to ensure it stays current and receives improvements and fixes made in their mainline branch.
