### ISSUE TITLE
Can't create surface in latest commits

### ISSUE THREAD

**Issue by johanlindfors** [microsoft/angle#23]
I'm trying to leverage the future-dev branch and in a Windows 8.1 app the eglCreateWindowSurface fails every time even though I've updated all libs, dll's and the templates as well.

Also talked to a colleague who have had the same issue with the available code...

Any ideas?

**Comment by austinkinross** [comment]
Hi,

Sorry for your problems. Could you try syncing to the latest version of the branch? I have just pushed a fix for this.

Thanks,
Austin

**Comment by johanlindfors** [comment]
Hi Austin, thanks for an impressive response time! ?

Yes, I've pulled the latest commit and rebuilt all the code, it now works as expected again!

Regards

Johan Lindfors
//coderox
Skickat fr?n Surface Pro 3
