### ISSUE TITLE
future_dev branch does not compile with Visual Studio 2013 Update 4

### ISSUE THREAD

**Issue by stammen** [microsoft/angle#26]
future_dev branch does not compile for Windows Store or Phone with Visual Studio 2013 Update 4

It looks like Update 4 added more Win32 API threading support for Windows Store

> D:\GitHub\angle-future-dev\src\common/tls.h(18): error C2220: warning treated as error - no 'object' file generated (........\src\common\tls.cpp)
> 4>D:\GitHub\angle-future-dev\src\common/tls.h(18): warning C4005: 'TLS_OUT_OF_INDEXES' : macro redefinition (........\src\common\tls.cpp)
> 4>          C:\Program Files (x86)\Windows Kits\8.1\Include\um\processthreadsapi.h(390) : see previous definition of 'TLS_OUT_OF_INDEXES'
> 4>D:\GitHub\angle-future-dev\src\common/tls.h(18): error C2220: warning treated as error - no 'object' file generated (........\src\libEGL\main.cpp)
> 4>D:\GitHub\angle-future-dev\src\common/tls.h(18): warning C4005: 'TLS_OUT_OF_INDEXES' : macro redefinition (........\src\libEGL\main.cpp)
> 4>          C:\Program Files (x86)\Windows Kits\8.1\Include\um\processthreadsapi.h(390) : see previous definition of 'TLS_OUT_OF_INDEXES'
> 4>........\src\common\utilities.cpp(492): error C2220: warning treated as error - no 'object' file generated
> 4>........\src\common\utilities.cpp(492): warning C4273: 'Sleep' : inconsistent dll linkage
> 4>          C:\Program Files (x86)\Windows Kits\8.1\Include\um\synchapi.h(908) : see previous definition of 'Sleep'
> 5>------ Build started: Project: All, Configuration: Release ARM ------
> 5>

**Comment by coopp** [comment]
I just updated future-dev with a fix that will allow Update 3 and Update 4 to compile properly.

**Comment by stammen** [comment]
Builds fine with Update 4. Thanks!

**Comment by stammen** [comment]
The latest ANGLE version works fine in the cocos2d-x v3 universal app built with Visual Studio 2013 Update 4. Thanks for fixing the ANGLE build.
