### ISSUE TITLE
glScissor has flipped y-coordinate

### ISSUE THREAD

**Issue by johanlindfors** [microsoft/angle#28]
It seems like when glScissor is called, I need to manually make sure the y coordinate is calculated differently than on other platforms. This is in the future-dev branch!

What used to be: 

glScissor(x,y,width,height);

now needs to be:

glScissor(x,<viewportheight> - y - height,width,height); (where <viewportheight> is the current height of the viewport :) )

Is this by design or a bug?

**Comment by coopp** [comment]
I haven't looked into this yet.  I will find some time this week to investigate.

**Comment by austinkinross** [comment]
Hi Johan, this was definitely a bug. It should have been fixed in my latest commit. 

Thanks for reporting the issue!

**Comment by stammen** [comment]
Builds and runs fine in cocos2d-x v3.3.
