### ISSUE TITLE
Impossible to add Advertising

### ISSUE THREAD

**Issue by pekayatt** [microsoft/angle#31]
Love the work and the last version of Angle is finally with a great framerate, but unfortunately it is impossible to add custom controls on the XAML as advertising.

Thats is a big game breaker if you are trying to create a freemium or ad supported game.

Please advice.

**Comment by austinkinross** [comment]
Hi pekayatt! Thank you for your kind words about our version of ANGLE.

Could you provide us with some more details about your problems? For example:
- What problems do you encounter when trying to add the advertising XAML controls?
- Which ad frameworks are you trying to use?

**Comment by pekayatt** [comment]
Hi austinkinross,

I have tried to use AdRotator, pubCenter, AdDuplex and AdMob. I could not find any 3rd party XAML control that I could use in the C++ project.

When adding the library (i.e. adRotator) by nugget or dropping the DLL on the both projects I cannot access the xaml control from a xaml on the shared project, or in the platform project.

Hope we find a workaround!

**Comment by austinkinross** [comment]
I can successfully add the AdDuplex framework to the SwapChainPanel template. I haven't tried the other frameworks.

I followed these instructions: https://adduplex.zendesk.com/hc/en-us/articles/200744262-Universal-SDK-for-XAML-apps-Windows-8-1-Windows-Phone-8-1-installation-and-usage

My XAML code in OpenGLESPage.xaml looks like this:

```
<Page
    x:Class="AppForOpenGLES23.OpenGLESPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:AppForOpenGLES23"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:ad="using:AdDuplex.Universal.Controls.WinPhone.XAML"
    mc:Ignorable="d">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="68"/> <!-- TODO: Use correct height for the ad -->
        </Grid.RowDefinitions>

        <SwapChainPanel x:Name="swapChainPanel" Grid.Row="0">
            <TextBlock Text="OpenGL ES and XAML" Foreground="White" HorizontalAlignment="Center" VerticalAlignment="Center" FontSize="30" />
        </SwapChainPanel>

        <ad:AdControl x:Name="adDuplexAd" AppId="YOUR_AppId_HERE" IsTest="True" Grid.Row="1"/>
    </Grid>

</Page>
```

And this is the result:

![image](https://cloud.githubusercontent.com/assets/8118471/5687486/f2515b0e-9801-11e4-8d7e-d09c28f69512.png)

Does this work for you?

**Comment by pekayatt** [comment]
Indeed I could use AdDuplex as you did there.

But I could only manage to make it work. Guys from AdRotator (https://github.com/Adrotator/AdrotatorV2/issues/52) said that the main problem is with all the other libraries.

So the only option is to wait for pubCenter or any other adProvider that in fact pay for clicks to publish their "new version" of the lib?

Thanks,

**Comment by austinkinross** [comment]
pubCenter works fine too.

I roughly followed this tutorial: http://msdn.microsoft.com/en-us/library/advertising-mobile-windows-phone-ads-walkthroughs-81-xaml-markup(v=msads.20).aspx

To add the reference, I right clicked on the Windows Phone project, went "Add->References...", then clicked on "Add New Reference...", then went to Extensions, then selected "Microsoft Advertising SDK for Windows Phone 8.1 (XAML).

My XAML looks like this:

```
<Page
    x:Class="AppForOpenGLES26.OpenGLESPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:AppForOpenGLES26"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:UI="using:Microsoft.Advertising.Mobile.UI"
    mc:Ignorable="d">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="50"/>
        </Grid.RowDefinitions>

        <SwapChainPanel x:Name="swapChainPanel" Grid.Row="0">
            <TextBlock Text="OpenGL ES and XAML" Foreground="White" HorizontalAlignment="Center" VerticalAlignment="Center" FontSize="30" />
        </SwapChainPanel>

        <UI:AdControl 
          AutoRefreshIntervalInSeconds="60" 
          ApplicationId="test_client" 
          AdUnitId="Image320_50" 
          HorizontalAlignment="Center" 
          Height="50" 
          IsAutoRefreshEnabled="True" 
          Width="320"
          Grid.Row="1"/>

    </Grid>
</Page>
```

![image](https://cloud.githubusercontent.com/assets/8118471/5713460/77874984-9a71-11e4-983e-9ca0cf3c3b5c.png)

**Comment by pekayatt** [comment]
I was mistaken to believe that it would now work if there was any error showing. Here I got the message that the AdControl was not found, but it works perfectly!

Gonna try out with AdMob as well, but these two are great already! 

Thank you very much!

**Comment by austinkinross** [comment]
Glad to help. Please reopen this issue if you experience more ANGLE-related advert problems.

**Comment by pekayatt** [comment]
Austin, sorry to bother again, but could not manage to make the adds recognize the taps from users.
Have tried this solution (https://social.msdn.microsoft.com/Forums/en-US/053fe091-8ffb-4d6f-a5ca-f39cff4af618/ads-not-responding-to-tap-or-click?forum=aiasdk), but this do not seem entirely compatible with the new project. My only answer in MSDN is that PubCenter do not support C++, but being so which Revenue Ad can we use? 
Thanks for the help always!
