### ISSUE TITLE
Why flipping textures?

### ISSUE THREAD

**Issue by amerkoleci** [microsoft/angle#34]
I saw your tutorials about loading dds and images using WIC and you flip images, why this?

Some engines around does not flip images (IE: https://github.com/gameplay3d/GamePlay/blob/next/gameplay/src/Texture.cpp)

Thanks

**Comment by amerkoleci** [comment]
Probably the samples (as I saw) renders in 2D and does not applies transformation (world-view-projection) and seams that
the UV coordinates are swapped.

**Comment by coopp** [comment]
You are correct that some engines do not need the flip of the texture memory :).  

We address this case by providing a vertical flip bool parameter in the texture loading helpers that gives the developer control over the flip behavior.

**Comment by amerkoleci** [comment]
Seams that you hacked the samples code to do fliping when it can be for sure optional, the parameter from my point of view should be optional and be false by default.

**Comment by coopp** [comment]
We appreciate your opinion on the flipping defaults and are glad that you are interested in using the loaders!

You are correct in that we did update the loader sample texture coordinates.  We did this to match a standard quad with texture coordinate order that is used in OpenGL.  The swapping of the texture coordinates is an optimal trick to correct upside texture rendering, but we didn't want to rely on that as the flip mechanism.

**Comment by amerkoleci** [comment]
Thank you, didn't want to be offensive, it was just point of view, anyway glad we had discussion about this :)

**Comment by coopp** [comment]
You were not offensive. :)  I am glad we had this discussion as well.

**Comment by austinkinross** [comment]
Hey amerkoleci,

The crux of the matter is that the data stored in DDS files and the data decoded by WIC starts in the upper left corner of the texture, and reads top-to-bottom. However, the data passed to GL APIs such as [glTexImage2D](https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexImage2D.xml) should start in the lower left of the texture image and read bottom-to-top:

> The first element corresponds to the lower left corner of the texture image. Subsequent elements progress left-to-right through the remaining texels in the lowest row of the texture image, and then in successively higher rows of the texture image. The final element corresponds to the upper right corner of the texture image.

This means that the the texture data has to be 'flipped' at some point. This could be done in:
1) the app by loading WIC/DDS textures that have already been flipped
2) the app in some other way (e.g. by swapping the UV coordinates as you suggest)
3) in the tutorials/helpers 
4) in ANGLE itself via an extension (but this adds a lot of complications without any performance benefit)

We didn't want to force apps to change their behavior to use these loaders, so we went with option (3) which should 'just work'. Of course, apps are free to disable (3) by setting 'verticalFlip' parameter to false and choosing option (1) or (2).

Hope this makes sense,
Austin

**Comment by amerkoleci** [comment]
Ok thats fine then, i was thinking about webgl stuff on texture handling, pixelStorei takes an UNPACK_FLIP_Y_WEBGL
