### ISSUE TITLE
Hope for supporting Windows 10 UAP

### ISSUE THREAD

**Issue by neuswcjr** [microsoft/angle#36]
I manually port the project for Windows 8.1 to Windows 10 UAP project,and it works fine on PC(10041), except for few compile issues. But the same application exited immediately after start on WIndows 10 for phone(2nd release). I hope you guys can provide more formal support for UAP in the future, such as proect templets,etc. After all, windows 10 is the future, isn't it?

PS. Forgive my poor English skills...

**Comment by coopp** [comment]
Hi neuswcjr,
  Yes, Windows 10 UAP will be coming.  We plan on adding the additional projects soon.
