### ISSUE TITLE
Templates not working in VS 2015 Community RC

### ISSUE THREAD

**Issue by Gerharddc** [microsoft/angle#38]
I have installed the templates for both Visual Studio 2013 and 2015 but they are not showing up in VS 2015 Community edition even though they do show up in the 2013 version.

**Comment by austinkinross** [comment]
Hello, thank you for reporting your issue!

Which templates aren't available in VS2015 for you? The Windows 10 templates or the Windows 8.1 templates?

The Windows 10 templates should be available in VS2015 by going "File -> New -> Project", then selecting "Templates -> Visual C++ -> Windows -> Windows Universal". If they aren't available then something has gone wrong, and we can help you fix it.

We don't currently install the Windows 8.1 templates in VS2015. We recommend using VS2013 to develop your Windows 8.1 and Windows Phone 8.1 ANGLE applications.

Thanks,
Austin

**Comment by Gerharddc** [comment]
Hi Austin,

It's unfortunate that you do not support 8.1 in 2015 as I would prefer to use it. I can confirm though that I am also not seeing the 10 templates in the folder that you suggested (and where assumed they would be). I am running on an 8.1 machine though if it makes any difference.

Regards,
Gerhard

**Comment by austinkinross** [comment]
Hi Gerhard,

Sorry for the slow reply. 

My understanding is that Visual Studio 2015 RC is currently in preview mode, and the license doesn't allow for apps to be published to the store. That is the main reason why we don't currently support the 8.1 templates in 2015.

I don't think the 8.1 machine should make a difference. Would you mind running 'install.bat' from the /templates/ directory, and sharing the output log of it on here? Hopefully that will help us understand your installation issue.

Thanks,
Austin

**Comment by Gerharddc** [comment]
Hi Austin,

Ok here's my output:

Check that this script is in the correct location
   Script has been launched from a directory called templates.
Setting the 'AngleRootPath' system environment variable
   Setting AngleRootPath to "C:\Users\Gerhard\Source\Repos\angle\templates.."
   Successfully set AngleRootPath system environment variable.
Installing ANGLE's Visual Studio 2013 templates
   Visual Studio 2013 templates directory found
   Removing old VS2013 UniversalCoreWindow template
   Removing old VS2013 UniversalSwapChainPanel template
   Removing old VS2013 DesktopHelloTriangle template
   Successfully installed latest Visual Studio 2013 templates.
Installing ANGLE's Visual Studio 2015 templates
   Visual Studio 2015 templates directory found
   Successfully installed latest Visual Studio 2015 templates.
Script complete.
Press any key to continue . . .

It does not seem to be giving any form of error.

Regards,
Gerhard de Clercq

**Comment by austinkinross** [comment]
Hi Gerard,

Thank you for the log, and many apologies for my delayed reply. The script simply copies the templates files from the ANGLE source tree to the custom VS template directory. Could you see if the templates have been installed to this directory?

C:\users\Gerhard\documents\visual studio 2015\templates\projecttemplates\windows\windows universal\

You may also wish to try our manual template installation instructions, [found here](https://github.com/MSOpenTech/angle/wiki/Installing-Templates).

Thanks again,
Austin

**Comment by austinkinross** [comment]
I'm closing this issue since it was on an pre-release version of Visual Studio, and we haven't received any recent reports of template issues. 

If you (or anyone else!) is still having issues with the templates then please feel free to reactivate this.

For future reference, the "/InstallVSTemplates" switch (https://msdn.microsoft.com/en-us/library/ms241279.aspx) may be helpful.

Thanks,
Austin
