### ISSUE TITLE
Is Pixel Art possible with lower resolution using a Nearest Neighbor scaler?

### ISSUE THREAD

**Issue by stevetranby** [microsoft/angle#42]
I'm trying to get our game running well on all WinPhone 8.1+ devices and we're having trouble with text not looking good at various resolutions due to it being anti-aliased probably in the hardware scale from the default DIB (735x410 on 1080p Lumia 930 device) resolution.

We pixelate and use NEAREST in our texture and GL calls.

**Comment by austinkinross** [comment]
Hi Steve,

Yes, the hardware overlay scaler in Windows phones doesn't use nearest neighbor.

One solution to this would be to render your game's content to a small offscreen surface. You could copy this to your window surface by rendering a textured quad using GL_NEAREST. There will still be performance benefits for this compared to rendering at full-resolution, but they won't be as great as using the hardware scaler.

I hope this helps, and let me know if you have any other questions.
Austin

**Comment by stevetranby** [comment]
Thanks for the info. 

I'm working with the cocos2d-x engine. Would you recommend doing this on the OpenGL side with a render texture or frame buffer, or should I modify the ANGLE part to do this with DirectX surfaces?

**Comment by austinkinross** [comment]
Apologies, I missed your reply. I'd strongly recommend doing this on the OpenGL ES side with a texture or offscreen framebuffer. This will have very similar performance to modifying the DirectX part of ANGLE.

Hope this helps!
