### ISSUE TITLE
Crash when using multithreaded on Windows 10 pc app

### ISSUE THREAD

**Issue by laudaicat** [microsoft/angle#45]
- My windows 10 pc app crash while mobile app didn't.
- I using 1 thread for load data while another thread rendering loading texture.

**Comment by coopp** [comment]
Hi laudaicat,
  Could you provide a simple repro app for the crash you are seeing?  I would like to understand this issue more in detail.
ANGLE as a code base is not fully thread safe.  Locks must be managed by the application to ensure safe access during rendering while working with multiple threads.

**Comment by stammen** [comment]
Hi Laudaicat,

Just like regular OpenGL ES you will need to setup and release the GL context from each thread. Otherwise you will not have a valid GL context from the second thread.

For example look at:

https://www.opengl.org/wiki/OpenGL_and_multithreading

**Comment by laudaicat** [comment]
``` c++
void SimpleRenderer::loaderThread(SimpleRenderer * pThis)
{

    EGLint contextAttrs[] =
    {
        EGL_CONTEXT_CLIENT_VERSION, 2,
        EGL_NONE
    };



    if (pThis->mEglContext == 0)
    {
        return;
    }


    EGLContext contex = EGL_NO_CONTEXT;
    EGLSurface surface = EGL_NO_SURFACE;

    // create a shared context for this thread
    contex = eglCreateContext(pThis->mEglDisplay, pThis->mEglConfig, pThis->mEglContext, contextAttrs);


    EGLint pbufferAttribs[] = {
        EGL_WIDTH, 1
        , EGL_HEIGHT, 1
        , EGL_TEXTURE_TARGET, EGL_NO_TEXTURE
        , EGL_TEXTURE_FORMAT, EGL_NO_TEXTURE
        , EGL_NONE
    };


    surface = eglCreatePbufferSurface(pThis->mEglDisplay, pThis->mEglConfig, pbufferAttribs);


    if (!eglMakeCurrent(pThis->mEglDisplay, surface, surface, contex))
    {
        return;
    }

    std::queue<GLuint> buffer;
    GLfloat vertexColors[] =
    {
        0.0f, 0.0f, 0.0f,
        0.0f, 0.0f, 1.0f,
        0.0f, 1.0f, 0.0f,
        0.0f, 1.0f, 1.0f,
        1.0f, 0.0f, 0.0f,
        1.0f, 0.0f, 1.0f,
        1.0f, 1.0f, 0.0f,
        1.0f, 1.0f, 1.0f,
    };

    while (true)
    {
        GLuint tmp;
        glGenBuffers(1, &tmp);

        assert(tmp != 0);

        glBindBuffer(GL_ARRAY_BUFFER, tmp);
        glBufferData(GL_ARRAY_BUFFER, sizeof(vertexColors), vertexColors, GL_STATIC_DRAW);
        glFlush(); // Problem happen here

        buffer.push(tmp);

        if (buffer.size() > 10)
        {
            glDeleteBuffers(1, &buffer.back());
            buffer.pop();
        }
        std::this_thread::sleep_for(std::chrono::milliseconds(1));
    }
}

void SimpleRenderer::setContextData(EGLDisplay display, EGLContext context, EGLSurface surface, EGLConfig config)
{
    mEglDisplay = display;
    mEglContext = context;
    mEglSurface = surface;
    mEglConfig = config;
    mThread = std::thread(&SimpleRenderer::loaderThread, this);
}
```

Problem happen when I added glFlush(); (windows pc app)
On android or windows mobile it work fine.

**Comment by laudaicat** [comment]
Draw function

``` c++
void SimpleRenderer::Draw()
{
    glEnable(GL_DEPTH_TEST);
    glClearColor(0.3f, 0.3f, 0.3f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
}
```

**Comment by coopp** [comment]
Hi laudaicat,
  Initializing an EGL display, context and surface on one thread and creating contexts and resources from another is just not supported.  ANGLE isn't thread safe enough to do that and I am not even sure that OpenGL ES is spec'd to handle it well either.  

I recommend that if you can, remove the requirement for multithreading in your app.
If you must have multithreading your app, then I recommend that you do your loading work on the separate thread and keep all rendering on the main thread.  This will keep the contexts and resources valid and in sync.

**Comment by laudaicat** [comment]
Thank you, i hope angle support multithread soon.
