### ISSUE TITLE
How to enable ES 3.0 in angle?

### ISSUE THREAD

**Issue by zhaijialong** [microsoft/angle#48]
Hi, I tried to use es 3.0 in the template sample on Win10 desktop. I set the `EGL_CONTEXT_CLIENT_VERSION` to 3 and changed the shader using in/out instead of attribute/varying, but I got the error `Shader compilation failed: ERROR: 0:1: 'in' : storage qualifier supported in GLSL ES 3.00 only`. And adding `#version 300 es` to the shader will result other parser errors.

**Comment by austinkinross** [comment]
Hi zhaijialong,

Adding `EGL_CONTEXT_CLIENT_VERSION` is correct and adding `#version 300 es' to the shaders is also correct. 

However, `#version 300 es` must go on its own line in the shader source given to glShaderSource, but the STRING macro used in our templates doesn't automatically add newline characters. Therefore, you must manually add a `\n` to the shader source like this:

```
// Vertex Shader source
const std::string vs = STRING
(   #version 300 es\n
    uniform mat4 uModelMatrix;
    uniform mat4 uViewMatrix;
    uniform mat4 uProjMatrix;
    in vec4 aPosition;
    in vec4 aColor;
    out vec4 vColor;
    void main()
    {
        gl_Position = uProjMatrix * uViewMatrix * uModelMatrix * aPosition;
        vColor = aColor;
    }
);

// Fragment Shader source
const std::string fs = STRING
(   #version 300 es\n
    precision mediump float;
    in vec4 vColor;
    out vec4 fragmentColor;
    void main()
    {
        fragmentColor = vColor;
    }
);
```

These shaders should compile, and the spinning cube should be drawn using ES 3.0.

Alternatively you could remove the 'STRING' macro and load the shader source code using a different method (e.g. from a file).

Hope this helps!
Austin

**Comment by zhaijialong** [comment]
It works. Thank you. : )

**Comment by Chandrashekharrr** [comment]
const vertexShaderSource = `
#version 300 es\n
#pragma vscode_glsllint_stage: vert\n

void main(){
    
    gl_position = vec4(0.0,0.0,0.0,1.0);
    gl_point_size = 150.0;
}`;


const fragmentShaderSource = `
#version 300 es\n
#pragma vscode_glsllint_stage: frag\n

precision mediump float;

out vec4 fragColor;

void main(){
    
    fragColor = vec4(1.0, 0.0, 0.0, 0.0);
}`;



const canvas = document.querySelector('canvas');
const gl = canvas.getContext('web');

const program = gl.createProgram();

const vertexShader = gl.createShader(gl.VERTEX_SHADER);
gl.shaderSource(vertexShader, vertexShaderSource);
gl.compileShader(vertexShader);
gl.attachShader(program, vertexShader);



const fragmentShader = gl.createShader(gl.FRAGMENT_SHADER);
gl.shaderSource(fragmentShader, fragmentShaderSource);
gl.compileShader(fragmentShader);
gl.attachShader(program, fragmentShader);

gl.linkProgram(program);

if(!gl.getProgramParameter(program, gl.LINK_STATUS)){

        console.log(gl.getShaderInfoLog(vertexShader));
        console.log(gl.getShaderInfoLog(fragmentShader));
}

gl.useProgram(program);

gl.drawArrays(gl.POINTS, 0,1);




where am i going wrong please help
Can anybody tell me whats wrong in my code
