### ISSUE TITLE
Cannot create a depth texture on Windows Phone 8.1.

### ISSUE THREAD

**Issue by comeradealexi** [microsoft/angle#49]
Is this possible? I'm having a problem because of this section in validationES2.cpp:

```
      case GL_DEPTH_STENCIL_OES:
        if (!context->getExtensions().depthTextures)
        {
            context->recordError(Error(GL_INVALID_VALUE));
            return false;
        }
```

This is my call:
        glTexImage2D(GL_TEXTURE_2D, 0, GL_DEPTH_COMPONENT, static_cast<GLsizei>(uiW), static_cast<GLsizei>(uiH), 0, GL_DEPTH_COMPONENT, GL_UNSIGNED_INT, NULL);

In this function 'DetermineDepthTextureSupport' where it determines depth texture support I found that it seems to be GL_DEPTH_COMPONENT32_OES which is causing depth textures entirely to not be supported. As a test, I removed this from the list of requiredFormats but didn't work.

Not sure if this is a bug or if I simply am not allowed to create depth textures with ANGLE?

I'm running on a Lumia 930.

Thanks! :+1:

**Comment by austinkinross** [comment]
Hi,

ANGLE doesn't support the GL_ANGLE_depth_texture extension on D3D11 Feature Level 9_3 hardware such as your Lumia 930, because 9_3 hardware doesn't support sampling from a depth/stencil texture in a shader, ANGLE does support this extension on higher Features Levels (Feature Level 10_0+), which are supported by modern desktop GPUs.

Hope this helps,
Austin

**Comment by comeradealexi** [comment]
Ah thanks so much for the reply, I wasn't aware of this. For anyone else coming across this problem, here is some info on Microsofts website regarding this:

https://msdn.microsoft.com/en-us/library/windows/apps/jj207010(v=vs.105).aspx

https://msdn.microsoft.com/en-us/library/windows/apps/jj662930(v=vs.105).aspx

**Comment by austinkinross** [comment]
Thanks for sharing! 

It's worth noting that ANGLE supports the core OpenGL ES 2.0 specification when run on Feature Level 9_3 hardware (except for some minor corner-cases, documented in our [Known Issues](https://github.com/MSOpenTech/angle/wiki/Known-Issues) page). Generally you shouldn't have to worry about the D3D Feature Level when using core OpenGL ES 2.0 features. 

Extension support is less predicable though. Some extensions are supported on Feature Level 9_3 devices while others (such as GL_ANGLE_depth_texture) are not. The best way to find out which extensions are supported is to query for the GL_EXTENSIONS string on the device.
