### ISSUE TITLE
glBindAttribLocation does not work with precompiled shaders for WP8

### ISSUE THREAD

**Issue by stammen** [microsoft/angle#5]
glBindAttribLocation does not work with precompiled shaders for WP8. The current work around is to use gl GetAttribLocation. Need to figure out how to support glBindAttribLocation with precompiled shaders.

**Comment by ghost** [comment]
no evidence of huge demand for this fix for WP8. might reconsider in the future. note: it works in the future-dev branch (WP8.1)
