### ISSUE TITLE
Universal app C# bindings support

### ISSUE THREAD

**Issue by Ingerdev** [microsoft/angle#50]
Do you plan to create C# universal app template and low-level bindings to c++ code?

**Comment by coopp** [comment]
Hi Ingerdev,
  We currently do not have any plans for creating a c# template with bindings to c++ opengl es code.  I will add this to our backlog so our team can track and discuss it.  Is there something specific you are looking for?

We are currently working on fixing some NuGet packaging issues to ensure that c# apps can consume our ANGLE.WindowsStore NuGet package (https://www.nuget.org/packages/ANGLE.WindowsStore).

Hope this helps!

**Comment by Ingerdev** [comment]
Lets assume i have C# project and just installed this nuget package. I will be forced to reproduce c++ EGL glue code in c#, isnt it?

**Comment by coopp** [comment]
Yes, you are correct.  You will have to do that work.  We don't have any current plans to reproduce the EGL/OpenGL ES API surface in c#.

**Comment by Ingerdev** [comment]
Ok. May be it will be helpful for you in future, cocos2d-x ver. 3/4/5 had similar layer (C++->C#), but they dropped it in newer versions.

**Comment by coopp** [comment]
Thanks Ingerdev!  That is good info, I will check that out.

**Comment by JimSEOW** [comment]
Any update?
Is there an example on this: "c# apps can consume our ANGLE.WindowsStore NuGet package"?

**Comment by JimSEOW** [comment]
@coopp We are using [ANGEL.WindowStore Nuget on C#](https://github.com/Microsoft/angle/issues/125#issue-240868317), please take a look and comment. Thank you
