### ISSUE TITLE
creating a texture with invalid data crashes in Release but not Debug

### ISSUE THREAD

**Issue by jglanfield** [microsoft/angle#51]
I had a scenario where creating a texture via glTexImage2D caused crashes in Release but not Debug. I managed to figure out my error. I was specifying the GL_RGBA format but only giving it a 3-channel image. Once I fixed my image data (i.e., made it a 4-channel image) as was well. I have no idea why it survives the texture generation in Debug mode but not Release.

**Comment by austinkinross** [comment]
Hi, apologies for the (very) slow reply here. 

Specifying GL_RGBA while only supplying enough data for 3 channels will cause ANGLE to read from undefined memory. For example, if you pass in 300 bytes of data to glTexImage2D but ANGLE tried to read 400 bytes, then that last 100 bytes may be invalid and cause ANGLE to crash. Debug builds are optimized less, and this 100 bytes of memory may just be initialized to zero.

OpenGL ES implementations rely on applications getting their parameters to APIs like glTexImage2D correct for these kinds of thing. I don't think there's anything we can do in ANGLE to help here.

Thanks a lot for reporting the issue though, and feel free to reopen if you have any more questions on this topic.

Thanks!
Austin
