### ISSUE TITLE
Cross platform OpenGLView for Xamarin.Forms?

### ISSUE THREAD

**Issue by JimSEOW** [microsoft/angle#64]
Given the example given here below, is it possible to extend Angle C++ to C# for implementing an OpenGLView extending Xamarin.Forms.Veiw to UWP? 
https://github.com/Gerharddc/CppGLESXamarin

Currently OpenGLView is only available to Android.

**Comment by austinkinross** [comment]
Hello, 

Yes, it is possible to extend that sample to UWP. The code to initialize and use ANGLE in UWP applications is exactly the same as the code used in Windows 8.1 or Windows Phone 8.1 apps, so the work to extend that project to UWP should just involve creating a new UWP Visual Studio project. You could ask on that GitHub page if the owner is considering adding a UWP VS project.

**Comment by JimSEOW** [comment]
Could you consider ( when u have time) create a simple Visual studio project demonstrating ANGLE in UWP (ARM). I believe the sample will be exciting to both the UWP and cross platform mobile communities. Xamarin comes with different WAYS to link >90% cross platform code sharing XAMARIN.Forms UIs to underlying native (e.g. OpenGL through ANGLE ) control or panel.

**Comment by austinkinross** [comment]
We have several C++ Visual Studio UWP templates which work on all available architectures (including ARM). Feel free to try out the [cross-platform Visual Studio OpenGL ES template](https://visualstudiogallery.msdn.microsoft.com/61b15204-e6ae-4f9a-a59a-b3d916e1bb3f) which targets  Android, iOS and Windows (UWP). Alternatively please try cloning this repository and running the template install script [("/templates/install.bat")](https://github.com/MSOpenTech/angle/tree/ms-master/templates).

**Comment by JimSEOW** [comment]
It would help a beginner if the **Automatic Steps** using the Install.bat lead to {root}/winrt/10/windows/src/angle.sln  that also include at least one UWP sample (e.g. triangle). 

YES. I see how the UWP ARM can be created.

Next, is to write a C# wrapper to make it possible to use Xamarin.Forms.View 

We hope this could have been a nice collaboration between Microsoft and Xamarin to apply what Xamarin team has done with UrhoSharp to create e.g. an up-to-date cross platform AngelSharp binder (e.g. perhaps through cppSharp) which will for once replace the OpenTK for the c# communtiy.

**Comment by JimSEOW** [comment]
I tried the [cross-platform Visual Studio OpenGL ES template](https://visualstudiogallery.msdn.microsoft.com/61b15204-e6ae-4f9a-a59a-b3d916e1bb3f). works! Thanks
