### ISSUE TITLE
Does angle support several gl contexts at the same time?

### ISSUE THREAD

**Issue by teshca** [microsoft/angle#65]
Hi

My question is not about shared contexts. It's rather about two independent conexts.
What I'm trying to achieve is to put two SwapChainPanels side by side on the same XAML page.

I started with angle demo application and extended it to display two spinnging cubes.
But after that application crashes after displaying several frames at random places, looks like unsyncronized access.

Is this scenario supported by ANGLE? Are there any sample you can point me at?

**Comment by austinkinross** [comment]
Hi, are you creating two EGL Contexts on the same EGL Display and using them on different threads at the same time? If so then yes, this will cause crashes like you're seeing.

You should avoid drawing to the two surfaces from separate threads. Instead, you should perform your rendering to each SwapChainPanel/surface serially, i.e. something like this:

```
eglMakeCurrent(display, surface1, suface1, context);
[draw to surface 1]
eglMakeCurrent(display, surface2, surface2, context);
[draw to surface 2]
```

Alternatively you should be able to create two EGL Displays, each with their own EGL Context and one EGL Surface (i.e. SwapChainPanel).

I'm afraid I don't know of any samples for this.

**Comment by teshca** [comment]
Well. I'm talking about second option.
I've created a custom control that is inherited from SwapChainPanel and holds Display, Context and Surface as private fileds. So each instance of that control has it's own Context. 
It works fine when I have only one instance of that control on the page, but crashed after I try to add one more.

**Comment by austinkinross** [comment]
How are you creating your EGL Display? If you're using eglGetPlatformDisplayEXT then note the following from the spec:

> Multiple calls made to eglGetPlatformDisplayEXT with the same "platform" and "native_display" will return the same EGLDisplay handle.

https://www.khronos.org/registry/egl/extensions/EXT/EGL_EXT_platform_base.txt

If you're using passing identical parameters to both calls to eglGetPlatformDisplayEXT then they'll both return the same EGL Display, which means both of your custom controls will use the same D3D11 device. This will cause crashes like you're seeing.

Some ways you could avoid this: 
1. Quick and easy way: pass different parameters to eglGetPlatformDisplayEXT. For example, having different values for EGL_PLATFORM_ANGLE_MAX_VERSION_MAJOR_ANGLE and EGL_PLATFORM_ANGLE_MAX_VERSION_MINOR_ANGLE should be enough.
2. Cleaner but more work: Create your own D3D device(s) and EGLDevices (using the EGL_ANGLE_device_creation_d3d11 extension) and use them to initialize your EGLDisplays.

**Comment by teshca** [comment]
Thanks. You are right. I'm using eglGetPlatformDisplayEXT as in Visual Studio template.
eglGetPlatformDisplayEXT(EGL_PLATFORM_ANGLE_ANGLE, EGL_DEFAULT_DISPLAY, defaultDisplayAttributes)
Indeed I get the same display in both of my instances of the control.

Changing DisplayAttributes i.e. min and max version is not work for me
I still get the same display even when call   eglGetPlatformDisplayEXT with different attributes.

Will try to implement your second suggestion.

**Comment by teshca** [comment]
It looks like I can solve the problem by passing different `displayId` in each control
`eglGetPlatformDisplayEXT(EGL_PLATFORM_ANGLE_ANGLE, (EGLNativeDisplayType)displayId++, defaultDisplayAttributes)`
Do you think it's safe to do so?

**Comment by austinkinross** [comment]
That will work in the current version of ANGLE, but it's relying on out-of-spec behavior that ANGLE currently has. It's not guaranteed that this will continue to work in future versions of ANGLE.

See /src/libANGLE/Display.cpp for how this works, in particular these lines of code:

```
Display *Display::GetDisplayFromAttribs(void *native_display, const AttributeMap &attribMap)
{
...
if (display == nullptr)
    {
        // Validate the native display
        if (!Display::isValidNativeDisplay(displayId))
        {
            return NULL;
        }

        display = new Display(EGL_PLATFORM_ANGLE_ANGLE, displayId, nullptr);
        displays->insert(std::make_pair(displayId, display));
    }
...
}
```

Note that isValidNativeDisplay() will always return true (which is the behavior you're relying on) but this is out-of-spec and may change in the future:

```
bool Display::isValidNativeDisplay(EGLNativeDisplayType display)
{
    // TODO(jmadill): handle this properly
    if (display == EGL_DEFAULT_DISPLAY)
    {
        return true;
    }

#if defined(ANGLE_PLATFORM_WINDOWS) && !defined(ANGLE_ENABLE_WINDOWS_STORE)
    if (display == EGL_SOFTWARE_DISPLAY_ANGLE ||
        display == EGL_D3D11_ELSE_D3D9_DISPLAY_ANGLE ||
        display == EGL_D3D11_ONLY_DISPLAY_ANGLE)
    {
        return true;
    }
    return (WindowFromDC(display) != NULL);
#else
    return true;
#endif
}
```

**Comment by teshca** [comment]
Ok. Thanks. Will use this as a workaround for now and implement proper display creation later with `eglGetPlatformDisplayEXT(EGL_PLATFORM_DEVICE_EXT, eglDevice, attributes);`

**Comment by austinkinross** [comment]
Great! I'm glad to hear that you're unblocked.

I'm closing this issue, but feel free to reactivate it if you continue to have problems with this scenario.
