### ISSUE TITLE
ResizeBuffers when SwapChainPanel size changed

### ISSUE THREAD

**Issue by teshca** [microsoft/angle#70]
Hi
I've a problem when resize my SwapChainPanel.
After panel is resized (change width 800<->500) I can still see several frames displayed with the old size. This leads to "blinking"

In similar scenario with "DirectX and Xaml demo" there is no blinking.
I can see that when sizeChanged in this demo ResizeBuffers is called for swapChain
but I don't see any call for it in ANGLE. Is there a reason we don't call ResizeBuffers in ANGLE ?

**Comment by teshca** [comment]
![2016-07-08_23-40-08](https://cloud.githubusercontent.com/assets/1832898/16700938/82eb513a-4565-11e6-944c-3e85931adcf7.png) Attaching an image of what I see when size changed.
`<SwapChainPanel x:Name="swapChainPanel">
        <Border BorderThickness="5" BorderBrush="Green"/>
        <TextBlock Text="OpenGL ES and XAML" Foreground="White" HorizontalAlignment="Center" VerticalAlignment="Center" FontSize="30" />
  </SwapChainPanel>`
Green border has already changed it's size, but content of SwapChain (cube) still has it's original wider size for some time.

**Comment by austinkinross** [comment]
Hi there, thanks a lot for reporting this and apologies for the delayed reply! 

We're currently snowed under with other work right now, but we will try to investigate this issue as soon as we can. Thanks for understanding.

**Comment by teshca** [comment]
Actually I realized that in fact ResizeBuffers caled from checkForOutOfDateSwapChain after swapRect
But I still can't understand if the picture above is normal or it's a bug.
Size of xaml control and size of buffers in swapchain panel is not in sync

**Comment by owolff** [comment]
I think that this is the same issue that causes https://bugreports.qt.io/browse/QTBUG-54905 in Qt. I investigated and came up with https://codereview.qt-project.org/169614 Unfortunately it only fixes the case where the window size is being decreased. Increasing the size of a window in Qt (when compiled with angle) still does not cause a proper resize of the content. So the patch is not complete, but perhaps someone gets an idea about what else might be missing.

**Comment by jbuckmccready** [comment]
I am having the same problems as owolff using Qt 5.7. I tested owolff's patch and it does fix the the top yoffset bug when decreasing the size of the window but it still has the problem when increasing the size.

Any update on this?

**Comment by austinkinross** [comment]
Hi there, I'm afraid we don't have any update on this issue yet. Our team will discuss it again at our next planning meeting next week.

**Comment by valbok** [comment]
https://codereview.appspot.com/6812076/

    Resizing a window larger results in the newly exposed region being invalidated
    but the old region is treated as valid.
    This can result in the old region no longer updating.

This was added to D3D9.

So decided to add the same fix to D3D11, which fixes flickering while resizing, in Qt:
https://codereview.qt-project.org/c/qt/qtbase/+/265881

**Comment by austinkinross** [comment]
Hi everyone, we strongly suggest that you use the master ANGLE repository going forward: https://opensource.google.com/projects/angle

If you still have these problems then I suggest contacting the master ANGLE mailing list here: https://groups.google.com/forum/#!forum/angleproject

Thanks
Austin
