### ISSUE TITLE
Enable CMake build for angle.

### ISSUE THREAD

**Issue by lygstate** [microsoft/angle#71]

**Comment by austinkinross** [comment]
Hi, thanks for your request!

This may be something that the master ANGLE project maintainers can help with. You could make the feature request on their discussion boards (available [here](https://groups.google.com/forum/#!forum/angleproject)).

**Comment by austinkinross** [comment]
Hi again,

I'm afraid I'm going to close out this issue. Creating CMake builds is a fairly large infrastructural change that we (at MS) are unlikely to make in the future given the minimal returns for the effort and complexity involved.

Please feel free to discuss this suggestion over on the master ANGLE discussion boards (linked to above). You may even wish to consider submitting your own change to the master ANGLE repository to add CMake support!

Note that if CMake support is added to the master branch then we will pick it up next time we merge master into ms-master on our GitHub page.

Thanks for your interest in ANGLE!
Austin
