### ISSUE TITLE
Exception when creating surface with collapsed swapchainpanel and fixed scale

### ISSUE THREAD

**Issue by teshca** [microsoft/angle#72]
In demo app
1. add  visibility collapsed to xaml
`<SwapChainPanel x:Name="swapChainPanel" Visibility="Collapsed" >`
2. specify any scale in CreateRenderSurface
`float customResolutionScale = 1.0f;`
`mRenderSurface = mOpenGLES->CreateSurface(swapChainPanel, nullptr, &customResolutionScale);`

Run application after this two steps, you will get an exception "Can't create surface"

The problem is that in function

`HRESULT SwapChainPanelNativeWindow::scaleSwapChain(const SIZE &windowSize, const RECT &clientRect)`

we do not check size fo zero and get NaN in here

`Size renderScale = {(float)windowSize.cx / (float)clientRect.right,
                        (float)windowSize.cy / (float)clientRect.bottom};`

**Comment by teshca** [comment]
This is only valid for surface creation. We also call this fuction when sizeChanged event fired but we never check if the result was a SUCCESS in that case

**Comment by austinkinross** [comment]
Hi there, thanks for reporting this! 

We've been snowed under with other work recently, but we will try to investigate this soon.

**Comment by austinkinross** [comment]
Hi there, apologies for the delay here. If you are still having trouble with this then please consider contacting the master ANGLE mailing list: https://groups.google.com/forum/#!forum/angleproject

Thanks
Austin
