### ISSUE TITLE
Waitable back buffers support

### ISSUE THREAD

**Issue by abucur** [microsoft/angle#73]
Hello!

Some applications require very low input latency and I was wondering if there are plans to support IDXGISwapChain2::GetFrameLatencyWaitableObject() and allowing the applications to wait on that handle before rendering a new frame.

I imagine it doesn't fit very well with the model of EGL/GL but it would be a nice addition to the package. I think adding a new pointer type for querySurfacePointerANGLE should be sufficient for this case from an API perspective.

**Comment by austinkinross** [comment]
Hi Andrei, thanks for the request.

I believe you have been in contact with other Microsoft employees about this, who may have suggested using glFinish immediately after eglSwapBuffers. Did this suggestion help improve your latency?

**Comment by abucur** [comment]
Not by a lot. It seems to be a problem with my system configuration. I see latency when dragging icons on my Desktop and in the UWP low latency sample. It's not ANGLE related. Feel free to close.

**Comment by austinkinross** [comment]
Hi there! I'm closing out this issue since it's over 3 years old. If you're still interested in this feature then please consider suggesting it over on the master ANGLE repository's mailing list here: https://groups.google.com/forum/#!forum/angleproject

Thanks
Austin
