### ISSUE TITLE
Holographic branch assertion failed on non-holographic FBO render target

### ISSUE THREAD

**Issue by mlfarrell** [microsoft/angle#79]
err: rx::GetAs(336):    ! Assert failed in rx::GetAs(336): ANGLE_HAS_DYNAMIC_TYPE(DestT*, src)

Assertion failed!

Program: ...0b9-cdf064f47eebVS.Debug_Win32.gccdr\libGLESv2.dll
File: C:\vs_projs\ms_angle_hololens\src\libANGLE/angletypes.h
Line: 336

more info:

```
ucrtbased.dll!67d85786()    Unknown
[Frames below may be incorrect and/or missing, no symbols loaded for ucrtbased.dll] 
[External Code] 
```

>   libGLESv2.dll!rx::GetAsrx::SurfaceRenderTarget11,rx::RenderTarget11(rx::RenderTarget11 \* src) Line 336    C++
>     libGLESv2.dll!rx::Framebuffer11::clear(const gl::Data & data, const rx::ClearParameters & clearParams) Line 105 C++
>     libGLESv2.dll!rx::FramebufferD3D::clear(const gl::Data & data, unsigned int mask) Line 101  C++
>     libGLESv2.dll!gl::Framebuffer::clear(const gl::Data & data, unsigned int mask) Line 617 C++
>     libGLESv2.dll!gl::Context::clear(unsigned int mask) Line 2090   C++
>     libGLESv2.dll!gl::Clear(unsigned int mask) Line 603 C++
>     libGLESv2.dll!glClear(unsigned int mask) Line 96    C++
>     AppForOpenGLES1.exe!vom::FrameBuffer::clear(unsigned int clearFlags) Line 189   C++
>     AppForOpenGLES1.exe!vui::Layer::render() Line 127   C++
>     AppForOpenGLES1.exe!vui::Layer::getBackingTexture() Line 177    C++
>     AppForOpenGLES1.exe!AppForOpenGLES1::SimpleRenderer::vuiTestCase1::__l2::void <lambda>(Windows::Foundation::IAsyncAction ^)::__l2::<lambda>() Line 457  C++
>     [External Code] 
>     AppForOpenGLES1.exe!AppForOpenGLES1::App::[Windows::ApplicationModel::Core::IFrameworkView]::Run() Line 141 C++
>     [External Code] 

: p

**Comment by mlfarrell** [comment]
Potential solution 
https://github.com/mlfarrell/angle/commit/1fc7cd2547dfc73165efe9ff209f4f445696890b

^^ requires RTTI which angle doesn't have on release builds.  Going to need to rethink this...

**Comment by mlfarrell** [comment]
Here we go

https://github.com/mlfarrell/angle/commit/4b19784298c2c39b7965f0500a7fb47965fc68da

**Comment by MikeRiches** [comment]
@mlfarrell: Thank you for letting us know. With the update we just made, we were able to remove this code and update holographic resources in a smarter way. This bug should be gone now.
