### ISSUE TITLE
Settings->System->Display->Size of text, apps... affects the image quality on Windows 10

### ISSUE THREAD

**Issue by dmitriano** [microsoft/angle#80]
There is some specific setting (Settings->System->Display->Size of text, apps...) in Windows 10 (both PC and Mobile) that changes the logical units XAML works with. If this setting is 100% then 1 logical unit equals to 1 physical pixel, if it is 200% then 1 logical unit is 2 physical pixels.
If I create an app based on [“XAML App for OpenGL ES (Universal Windows)” template in VS2015](http://developernote.com/2015/11/combining-opengl-and-xaml-together-in-a-windows-store-app-uwp/), this setting significantly affects the final image quality. Please, see the VIDEO demonstrating the difference between OpenGLES app (at the left side) and DirectX app (at the right side) when the setting is 200%.
I did not investigate this problem in details, but at least I noticed that function mOpenGLES->GetSurfaceDimensions() returns the size of SwapChainPanel control in XAML logical units, but not in physical pixels, so physical surface size is less than physical SwapChainPanel size. I wander if there is a workaround in my app, or probably some small fix that takes into account this 200% can be made in ANGLE? This is especially frustrating effect on Windows 10 Mobile devices, because, for example, on Lumia 650 this setting is 200% by default.

**Comment by abucur** [comment]
There's a page on their Wiki explaining the solution to this problem:
https://github.com/Microsoft/angle/wiki/Scaling-your-app-to-run-at-different-resolution-on-the-device

Basically you need to pass the screen scale factor when creating the surface using the EGLRenderResolutionScaleProperty property.

**Comment by austinkinross** [comment]
Yes, please try using the EGLRenderResolutionScaleProperty  property.

**Comment by dmitriano** [comment]
It works! Thank you!
