### ISSUE TITLE
ANGLE does not compile?

### ISSUE THREAD

**Issue by dmitriano** [microsoft/angle#81]
With the latest version of ANGLE sources from ms-master branch I got the following compiler errors while building angle\winrt\10\src\angle.sln:

_1>------ Build started: Project: copy_scripts, Configuration: Debug Win32 ------
1>  Copying commit_id.bat to D:\Repos\angle\winrt\10\src\Debug_Win32\obj/global_intermediate/angle\commit_id.bat
1>          1 file(s) copied.
1>  Copying copy_compiler_dll.bat to D:\Repos\angle\winrt\10\src\Debug_Win32\obj/global_intermediate/angle\copy_compiler_dll.bat
1>          1 file(s) copied.
2>------ Build started: Project: commit_id, Configuration: Debug Win32 ------
2>  Generating ANGLE Commit ID
3>------ Build started: Project: angle_common, Configuration: Debug Win32 ------
3>  Float16ToFloat32.cpp
3>  MemoryBuffer.cpp
3>  angleutils.cpp
3>  debug.cpp
3>  mathutil.cpp
3>  string_utils.cpp
3>  tls.cpp
3>  utilities.cpp
3>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\winrt\wrl\module.h(1712): error C2220: warning treated as error - no 'object' file generated (compiling source file ......\src\common\utilities.cpp)
3>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\winrt\wrl\module.h(1712): warning C4467: usage of ATL attributes is deprecated (compiling source file ......\src\common\utilities.cpp)
3>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\winrt\wrl\module.h(1712): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings (compiling source file ......\src\common\utilities.cpp)
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
_

Probably I have a wrong version of SDK or I downloaded a wrong version of ANGLE sources? I am using VS2015 with Update 3.

**Comment by austinkinross** [comment]
Hi, thanks for reporting this! This is an error that occurs when ANGLE is compiled with VS 2015 Update 3. I've just pushed a fix to the ms-master branch which should fix it for you.

Feel free to reactivate this thread if you experience more compilation issues.

**Comment by austinkinross** [comment]
@MikeRiches, this issue might also occur in the ms-holographic-experimental branch?
