### ISSUE TITLE
Changing Windows 10 Mobile Device orientation affects the transparency of the image

### ISSUE THREAD

**Issue by dmitriano** [microsoft/angle#82]
The transparency of the cube drawn by UWP application based on “XAML App for OpenGL ES (Universal Windows)” template depends on Mobile Device orientation. Please see [detailed description HERE](http://developernote.com/2016/08/testing-xaml-app-for-opengl-es-on-windows-10-mobile-device/).
Steps to reproduce: get the sample app sources from https://github.com/dmitriano/AppForOpenGLES2 and run the app on a real mobile device. Change the device orientation from portrait to landscape and vice versa.

My environment:
VS2015 Update 3 (or probably 3.1, but Help-About shows Update 3)
app Target Platform Version 10.0.10586.0 (UWP)
Mobile Device: Lumia 650

**Comment by austinkinross** [comment]
Strange issue! We'll try to investigate this soon. Thanks for reporting it.

**Comment by austinkinross** [comment]
Hi there, please consider contacting the master ANGLE repository's mailing list (https://groups.google.com/forum/#!forum/angleproject) or the DirectX Discord channel (https://devblogs.microsoft.com/directx/hello-discord/) if you are still having problems here.

Thanks
Austin
