### ISSUE TITLE
C# interop doesn't behave as expected

### ISSUE THREAD

**Issue by lwansbrough** [microsoft/angle#83]
This is more of a request for help than a bug. I'm not very familiar with C++. I'm using OpenGL.Net to call `eglCreateWindowSurface` using their mapped method `Egl.CreateWindowSurface`. I want to pass a `PropertySet` to C++ but I'm getting an "Attempted to read or write protected memory" error.

This is what I'm attempting to replicate in C#: https://github.com/Microsoft/angle/blob/ms-holographic-experimental/templates/10/Windows/Universal/CoreWindowUniversal/app.cpp#L332

I'm passing the `PropertySet` as an `IntPtr` (I'm using `GCHandle.Alloc`) as per the OpenGL.Net implementation here: https://github.com/luca-piccioni/OpenGL.Net/blob/master/OpenGL.Net/Egl.VERSION_1_0.cs#L751

Is there a way to get this to work?

I changed the `win` IntPtr to `IntPtr.Zero` which stopped the error, so I have to assume the `PropertySet` is the offending code.

**Comment by austinkinross** [comment]
Hi, can you share the code you're using to create your PropertySet in C#? 

ANGLE is expecting the PropertySet to be a WinRT PropertySet (hence the carot and the "ref new PropertySet();" in the line of template code you linked to) so I imagine the PropertySet will need to be initialized in a very specific way in C# for this to work.

**Comment by lwansbrough** [comment]
Here's how I'm doing it.

``` c#
        private IntPtr CreateEglContext(HolographicSpace holographicSpace, SpatialStationaryFrameOfReference stationaryReferenceFrame)
        {
            IntPtr context;
            int[] configAttribs = new int[]
            {
                Egl.RED_SIZE, 8,
                Egl.GREEN_SIZE, 8,
                Egl.BLUE_SIZE, 8,
                Egl.ALPHA_SIZE, 8,
                Egl.DEPTH_SIZE, 8,
                Egl.STENCIL_SIZE, 8,
                Egl.NONE
            };

            int[] contextAttribs = new int[]
            {
                Egl.CONTEXT_CLIENT_VERSION, 2,
                Egl.NONE
            };

            int[] surfaceAttribs = new int[] {
                EGL_ANGLE_SURFACE_RENDER_TO_BACK_BUFFER, Egl.TRUE,
                Egl.NONE
            };

            int[] defaultDisplayAttribs = new int[]
            {
                EGL_PLATFORM_ANGLE_TYPE_ANGLE, EGL_PLATFORM_ANGLE_TYPE_D3D11_ANGLE,
                EGL_ANGLE_DISPLAY_ALLOW_RENDER_TO_BACK_BUFFER, Egl.TRUE,
                EGL_PLATFORM_ANGLE_ENABLE_AUTOMATIC_TRIM_ANGLE, Egl.TRUE,
                Egl.NONE
            };

            int[] fl9_3DisplayAttributes = new int[]
            {
                // These can be used to request ANGLE's D3D11 renderer, with D3D11 Feature Level 9_3.
                // These attributes are used if the call to eglInitialize fails with the default display attributes.
                EGL_PLATFORM_ANGLE_TYPE_ANGLE, EGL_PLATFORM_ANGLE_TYPE_D3D11_ANGLE,
                EGL_PLATFORM_ANGLE_MAX_VERSION_MAJOR_ANGLE, 9,
                EGL_PLATFORM_ANGLE_MAX_VERSION_MINOR_ANGLE, 3,
                EGL_ANGLE_DISPLAY_ALLOW_RENDER_TO_BACK_BUFFER, Egl.TRUE,
                EGL_PLATFORM_ANGLE_ENABLE_AUTOMATIC_TRIM_ANGLE, Egl.TRUE,
                Egl.NONE
            };

            int[] warpDisplayAttributes = new int[]
            {
                // These attributes can be used to request D3D11 WARP.
                // They are used if eglInitialize fails with both the default display attributes and the 9_3 display attributes.
                EGL_PLATFORM_ANGLE_TYPE_ANGLE, EGL_PLATFORM_ANGLE_TYPE_D3D11_ANGLE,
                EGL_PLATFORM_ANGLE_DEVICE_TYPE_ANGLE, EGL_PLATFORM_ANGLE_DEVICE_TYPE_WARP_ANGLE,
                EGL_ANGLE_DISPLAY_ALLOW_RENDER_TO_BACK_BUFFER, Egl.TRUE,
                EGL_PLATFORM_ANGLE_ENABLE_AUTOMATIC_TRIM_ANGLE, Egl.TRUE,
                Egl.NONE
            };

            int[] configCount = new int[1];
            IntPtr[] configs = new IntPtr[8];

            if (Egl.BindAPI(Egl.OPENGL_ES_API) == false)
                throw new InvalidOperationException("No OpenGL ES API");

            if ((display = Egl.GetPlatformDisplayEXT(EGL_PLATFORM_ANGLE_ANGLE, IntPtr.Zero, defaultDisplayAttribs)) == IntPtr.Zero)
                throw new InvalidOperationException("Unable to get EGL display");

            if (!Egl.Initialize(display, null, null))
            {
                if ((display = Egl.GetPlatformDisplayEXT(EGL_PLATFORM_ANGLE_ANGLE, IntPtr.Zero, fl9_3DisplayAttributes)) == IntPtr.Zero)
                    throw new InvalidOperationException("Unable to get EGL display");

                if (!Egl.Initialize(display, null, null))
                {
                    if ((display = Egl.GetPlatformDisplayEXT(EGL_PLATFORM_ANGLE_ANGLE, IntPtr.Zero, warpDisplayAttributes)) == IntPtr.Zero)
                        throw new InvalidOperationException("Unable to get EGL display");

                    if (!Egl.Initialize(display, null, null))
                        throw new InvalidOperationException("Unable to initialize EGL");
                }
            }

            if (!Egl.ChooseConfig(display, configAttribs, configs, 1, configCount))
                throw new InvalidOperationException("Unable to choose configuration");

            holographicSpaceHandle = GCHandle.Alloc(holographicSpace);

            //PropertySet surfaceCreationProperties = new PropertySet
            //{
            //    { "EGLNativeWindowTypeProperty", (IntPtr)holographicSpaceHandle }
            //};

            PropertySet surfaceCreationProperties = new PropertySet();
            surfaceCreationProperties.Add("EGLNativeWindowTypeProperty", (IntPtr)holographicSpaceHandle);

            //if (stationaryReferenceFrame != null)
            //{
            //    stationaryReferenceFrameHandle = GCHandle.Alloc(stationaryReferenceFrame);
            //    surfaceCreationProperties.Add("EGLBaseCoordinateSystemProperty", (IntPtr)stationaryReferenceFrameHandle);
            //}

            GCHandle surfaceCreationPropertiesHandle = GCHandle.Alloc(surfaceCreationProperties);

            if ((surface = Egl.CreateWindowSurface(display, configs[0], (IntPtr)surfaceCreationPropertiesHandle, surfaceAttribs)) == IntPtr.Zero)
                throw new InvalidOperationException("Unable to create EGL fullscreen surface");

            if ((context = Egl.CreateContext(display, configs[0], IntPtr.Zero, contextAttribs)) == IntPtr.Zero)
                throw new InvalidOperationException("Unable to create context");

            return context;
        }
```

**Comment by lwansbrough** [comment]
@austinkinross Any hints? You mentioned "the PropertySet will need to be initialized in a very specific way in C# for this to work" -- I'm curious what that might look like! Cheers.

**Comment by austinkinross** [comment]
I'm afraid this is quite far outside my area of expertise. :-) 

I would investigate trying to create a mini C++ 'Windows Runtime Component' to solve this. There's a template for WinRT components in VS2015's 'New Project' menu (C++/Windows/Universal).

After you've created a new WinRT component in your VS solution, add a reference to it from your C# project. Then, in the WinRT component, try adding a function that takes in the various parameters for eglCreateWindowSurface, except replace native_window with a PropertySet^. You can then make this function call the 'real' eglCreateWindowSurface.

As a very quick hacky example, Class1.h in the WinRT component could look something like this:

```
#pragma once

#include "EGL/egl.h"
#include "EGL/eglext.h"
#include "EGL/eglplatform.h"

using namespace Windows::Foundation::Collections;

namespace RuntimeComponent1
{
    public ref class Class1 sealed
    {
    public:
        Class1();

        unsigned __int64 EglCreateWindowSurface(unsigned __int64 display, unsigned __int64 config, PropertySet^ propertySet);
    };
}
```

And Class1.cpp could look like this:

```
#include "pch.h"
#include "Class1.h"

using namespace RuntimeComponent1;
using namespace Platform;

Class1::Class1()
{
}

unsigned __int64 Class1::EglCreateWindowSurface(unsigned __int64 display, unsigned __int64 config, PropertySet^ propertySet)
{
    const EGLint surfaceAttributes[] =
    {
        // EGL_ANGLE_SURFACE_RENDER_TO_BACK_BUFFER is part of the same optimization as EGL_ANGLE_DISPLAY_ALLOW_RENDER_TO_BACK_BUFFER (see above).
        // If you have compilation issues with it then please update your Visual Studio templates.
        EGL_ANGLE_SURFACE_RENDER_TO_BACK_BUFFER, EGL_TRUE,
        EGL_NONE
    };

    return (unsigned __int64)eglCreateWindowSurface((EGLDisplay)display, (EGLConfig)config, reinterpret_cast<IInspectable*>(propertySet), surfaceAttributes);
}
```

Then your C# code could look something like this:

```
using RuntimeComponent1;
...
PropertySet propertySet = new PropertySet();
// Initialize the property set;

Class1 c = new Class1();
var surface = c.EglCreateWindowSurface(display, config, propertySet);
```

I'm afraid I don't have time to tidy this up right now, but hopefully you get the gist. :-) 

You would also have to make sure that you pass the right values into Class1::EglCreateWindowSurface. I don't know if 'unsigned __int64' is the right type to be using- one of the other [base data types](https://msdn.microsoft.com/en-us/library/windows/desktop/br205768%28v=vs.85%29.aspx) may be better.

Hope this helps! Let me know if something's not clear. I'll also ask around and see if anyone else knows a better solution...

**Comment by lwansbrough** [comment]
Interesting, this looks like a plausible solution. Thanks! I'll give it a shot and get back to you.

**Comment by JimSEOW** [comment]
@lwansbrough  please provide link to your c# project once you get it working. This will be great. Thanks!

**Comment by lwansbrough** [comment]
I received a response on StackOverflow that suggests using `Marshal.GetIUnknownForObject()` to obtain an unmanaged pointer to the memory. This is causing a `DXGI_SWAP_CHAIN_DESC.OutputWindow is not a valid window handle.` error though. Unsure how to proceed. The problem with @austinkinross solution is that it requires executing a substantial amount of logic inside that Windows Runtime Component, because you can't pass  Class1::EglCreateWindowSurface an IntPtr (EGLDisplay is an IntPtr, not an int64.) Perhaps there's a way to fix this. I'd prefer marshaling because although it's pretty low level, it keeps everything in one project.

**Comment by JimSEOW** [comment]
Is this link useful?
http://www.instructables.com/id/C-OpenGL-ES-Viewer-in-C/step4/Create-the-Windows-Platforms-support-layer/

**Comment by lwansbrough** [comment]
@JimSEOW Mmm, not really. That's all in C++ whereas I'm working in C#. The crux of the issue right now is I have a C# object that I need to pass to C++, and it would appear as though the final implementation of the C++ will be unmanaged.

**Comment by lwansbrough** [comment]
Here's what I'm working on if anyone is interested: https://github.com/lwansbrough/HolographicJS

**Comment by JimSEOW** [comment]
I think these are good starting points for creating c# wrappers for unmanaged DLLs provided by Angle
https://github.com/koush/OpenGLES/blob/master/gl.cs [LibGLESv2.dll]
https://github.com/koush/OpenGLES/blob/master/egl.cs [libEGL.dll]

**Comment by hamarb123** [comment]
@lwansbrough View the code on my library.
https://github.com/hamarb123/hamarb123.SharpGLES/blob/master/hamarb123.SharpGLES/EGL.cs
In stead of an IntPtr, in UWP you need to use an [MarshalAs(UnmanagedType.IInspectable)] object,
Check out all of the code here: https://github.com/hamarb123/hamarb123.SharpGLES
My library is fully functional on both UWP and the .NET Framework.

**Comment by austinkinross** [comment]
Hi there, I'm closing out this issue since it's now about 3 years old. If you'd like to have further discussion on this topic then I suggest contacting the main ANGLE repository's mailing list here: https://groups.google.com/forum/#!forum/angleproject

Thanks
Austin
