### ISSUE TITLE
What blending operation is used to merge transparent OpenGL surface with XAML?

### ISSUE THREAD

**Issue by dmitriano** [microsoft/angle#85]
Hello!
What blending operation is used to merge OpenGL surface with XAML, if I draw a transparent image in SwapChainPanel (with OpenGL calls)? Is it possible to change it to glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)? If my question sounds a bit wired, [my article describing the experimentation I done with a UWP app](http://developernote.com/2016/08/drawing-a-transparent-image-with-opengl-es-in-a-xaml-app/) will give you more detailed picture on what I am asking.

**Comment by austinkinross** [comment]
Hi, apologies for the delayed reply. The blending mode isn't customizable. On some hardware (particularly phones), the blending operation between surfaces will be performed by highly optimized hardware that may not be configurable.

The alpha mode of the surface can be configured, but not using an Open GL ES API. You would have to modify ANGLE's source code yourself by changing the D3D swapchain's alpha mode to another valid [DXGI_ALPHA_MODE ](https://msdn.microsoft.com/en-us/library/windows/desktop/hh404496%28v=vs.85%29.aspx) value.

```
    swapChainDesc.AlphaMode =
        containsAlpha ? DXGI_ALPHA_MODE_PREMULTIPLIED : DXGI_ALPHA_MODE_IGNORE;
```

https://github.com/Microsoft/angle/blob/ms-master/src/libANGLE/renderer/d3d/d3d11/winrt/SwapChainPanelNativeWindow.cpp

**Comment by dmitriano** [comment]
Thank you very much, for detailed explanation.
