### ISSUE TITLE
Compiled Binaries for Desktop

### ISSUE THREAD

**Issue by mattleibow** [microsoft/angle#88]
Hi team! I was wondering if there are any "official" binaries for Windows desktop? I see there are two NuGets:
- https://www.nuget.org/packages/ANGLE.WindowsStore
- https://www.nuget.org/packages/ANGLE.WindowsStore.win81

Are there something similar for Desktop, either NuGet or otherwise?

**Comment by JimSEOW** [comment]
@mattleibow 
For Windows 10, I follow 
https://github.com/Microsoft/angle/wiki/Installing-Templates (both automatic and manual) to create ANGLE.WindowsStore [UWP] (x86, x64[Desktop] and ARM [for Windows 10 mobile])

I am not sure if the ANGLE.WindowsStore(UWP) nuget provides the ARM version.

**Comment by mattleibow** [comment]
@JimSEOW The Windows 10 UWP NuGet does have ARM (Win32/x64/ARM). But, I am looking for some pre-built binaries that I can use on Windows 7/8.x - a .NET 4.5 Classic Desktop application. #LazyGuy #DoNotWantToBuild

**Comment by JimSEOW** [comment]
Ref: https://github.com/arkenthera/cef3d

**Angle and Direct3D support for Windows XP, Vista, Win7, and newer**
- d3dcompiler_43.dll (required for Windows XP)
- d3dcompiler_47.dll (required for Windows Vista and newer)
- libEGL.dll
- libGLESv2.dll

**Comment by austinkinross** [comment]
Hi Matthew, we don't redistribute binaries for Windows desktop.

**Comment by austinkinross** [comment]
I'm closing this issue, but feel free to reactivate it if you have further questions on this topic.
