### ISSUE TITLE
OpenGL surface from SwapChainPanel declared in XAML in C#

### ISSUE THREAD

**Issue by JimSEOW** [microsoft/angle#89]
The Angle VC++ OpenGLES template demonstrate how to obtain [OpenGL surface from SwapChainPanel](http://developernote.com/2015/11/combining-opengl-and-xaml-together-in-a-windows-store-app-uwp/)

Angle provides [2 ways to do that](https://msopentech.com/blog/2014/11/06/creating-corewindow-and-swapchainpanel-window-surfaces-in-angle/#)

Question: How to port that to C#
I am stuck with 
`reinterpret_cast<IInspectable*>(swapChainPanel)`

How to do that using unsafe method or complete c# code?

Running out of ideas :-(

Is there other way to do that?

**Comment by mattleibow** [comment]
Hi @JimSEOW, this is what I am starting with. (Got to clean up, but then this is what I am going to use for SkiaSharp.

I used: `[MarshalAs(UnmanagedType.IInspectable)]`

``` csharp
using EGLDisplay = System.IntPtr;
using EGLSurface = System.IntPtr;
using EGLConfig = System.IntPtr;
using EGLNativeWindowType = System.Object;

[DllImport(libEGL)]
public static extern EGLSurface eglCreateWindowSurface(
    EGLDisplay dpy, 
    EGLConfig config, 
    [MarshalAs(UnmanagedType.IInspectable)] EGLNativeWindowType win, 
    int[] attrib_list);
```

Check out my entire code file here:
https://gist.github.com/mattleibow/eacb9c9e87f306b218d99c713c532a82

**Comment by mattleibow** [comment]
That will work, but if I try and add other types to the `PropertySet`, it breaks :( ie:

``` csharp
surfaceCreationProperties.Add("EGLRenderResolutionScaleProperty", PropertyValue.CreateSingle(2));
```

**Comment by mattleibow** [comment]
I created a SO question here as this may not (is not) be directly related to ANGLE: http://stackoverflow.com/questions/39432377/marshalling-eglrenderresolutionscaleproperty-to-angle-from-c-sharp-using-p-inv

**Comment by mattleibow** [comment]
It may be the case that there is a better/another way to pass the scaling in... Or some other way to set the buffer size (since if the size is wrong, or not scaled, it is blurry on hi-dpi devices)

**Comment by JimSEOW** [comment]
Thanks to @mattleibow, the following samples are now working.
XAML App for OpenGL ES (Universal Windows) Visual C#

**Comment by JimSEOW** [comment]
@mattleibow please take a look at this [discussion ](https://github.com/Microsoft/WindowsTemplateStudio/issues/561)to bridge Remix3D (indoor) to (outdoor) Mixed Reality.

**Comment by JimSEOW** [comment]
We continue to [this](https://github.com/Microsoft/angle/issues/125)
