### ISSUE TITLE
Multiple Render Targets (MRT)

### ISSUE THREAD

**Issue by ghost** [microsoft/angle#90]
Hi.
Is Multiple Render Targets (MRT) supported?

Thanks!

**Comment by austinkinross** [comment]
Hi, ANGLE supports MRT in both ES3 and ES2. 

MRT is mandatory in ES3 (with GL_MAX_DRAW_BUFFERS >= 4), and ANGLE supports it in ES2 via the GL_EXT_draw_buffers extension.

**Comment by austinkinross** [comment]
(Feel free to reactivate this issue if you have further questions on this topic)
