### ISSUE TITLE
Unable to initialize GLES3 context with EGL_EXPERIMENTAL_PRESENT_PATH_FAST_ANGLE

### ISSUE THREAD

**Issue by abucur** [microsoft/angle#94]
When requesting a GLES3 context ANGLE specifically checks for the conformant flag on the config object against the EGL_OPENGL_ES3_BIT_KHR bit mask.

However, the flag is cleared when EGL_EXPERIMENTAL_PRESENT_PATH_FAST_ANGLE attribute is set (event though DX level is > 10.0) when creating the display so instantiating a GLES3 context is impossible.

Without the EGL_EXPERIMENTAL_PRESENT_PATH_FAST_ANGLE I've also noticed there are flickers when resizing a window with a SwapChainPanel even though the rendering code checks for surface size changes before rendering a frame. With EGL_EXPERIMENTAL_PRESENT_PATH_FAST_ANGLE it works correctly.

**Comment by abucur** [comment]
It seems this was fixed at a certain point by @austinkinross :
https://github.com/Microsoft/angle/commit/e0a02ffcdaa58405c7660a552e723606f5ae12a9

but somehow the change was lost (probably after a merge). Could you put it back and create a new release? It would be a waste to have ANGLE officially support GLES3 and not be able to use it with EGL_EXPERIMENTAL_PRESENT_PATH_FAST_ANGLE.

Thanks!

**Comment by abucur** [comment]
I've noticed there was a commit in April that fixed exactly this issue that but was lost somehow during that time:
https://github.com/Microsoft/angle/commit/e0a02ffcdaa58405c7660a552e723606f5ae12a9

I would appreciate if you could reapply it and post a new Nuget package with that. Thanks!

**Comment by abucur** [comment]
(Sorry for reopening, I just miss-clicked on the close button)

**Comment by austinkinross** [comment]
Hey Andrei, thanks for reporting the issue and apologies for not responding sooner!

I'll try to investigate this and publish a new NuGet package soon, hopefully tomorrow.

**Comment by austinkinross** [comment]
Hi, I've pushed the fix to the ms-master branch and published a new NuGet package: https://www.nuget.org/packages/ANGLE.WindowsStore/2.1.11

Thanks for reporting this!
