### ISSUE TITLE
What conditions would lead to "Failed to find a valid index into a holographic camera, HRESULT: 0x0"

### ISSUE THREAD

**Issue by lwansbrough** [microsoft/angle#96]
I'm running into the above error during a call to `glDrawElementsInstancedANGLE` -- what are some plausible causes of this? I see that my `HolographicNativeWindow` instance doesn't have any cameras when calling `holographicNativeWindow->GetCameraIds()` (this happens inside `SurfaceD3D::getAttachmentRenderTarget`)

**Comment by austinkinross** [comment]
@MikeRiches Any ideas?

**Comment by lwansbrough** [comment]
@austinkinross Hey sorry, forgot to update you guys. I think the problem ended up being a race condition related to how my application was calling that method.

I got my JS HoloLens rendering application working thanks to your work in this fork!

**Comment by austinkinross** [comment]
Glad your issue is resolved! I'm closing out this thread, but feel free to reactivate it if you're having further problems here.
